### ISSUE TITLE
Not really an issue, but have you guys thought of doing it for Swift?

### ISSUE THREAD

**Issue by VergaraF** [istornz/iPokeGo#10]
Sadly I have no idea about Objective-C, and I would like to contribute to this project as well... Have you thought of portraying this to Swift?

**Comment by istornz** [comment]
Thx for your help !
For me, I prefer Obj-C (i'm more experienced in this langage) and I work with Xcode 8 (to compile on my iOS 10 iPhone), so to port this project you have to use Swift 3.0 in beta :/

**Comment by ericlewis** [comment]
@istornz you can actually use 2.3 with Xcode 8. It's a flag for using legacy swift.
