### ISSUE TITLE
Deploy changes from server or app?

### ISSUE THREAD

**Issue by PaleHaunt** [istornz/iPokeGo#100]
I want to be able to change my Scan-Delay and my Num-Threads on the app. I figure I need to do this server side on Haroku. The problem is, I can't figure out how to deploy the changes. I am struggling with it all. The app currently runs, I just want to raise the speed. Any suggestions? Dropbox won't link for some reason on Heroku and the github won't let me go private unless I pay the monthly fee... The Heroku deploy won't work either, as the code won't make a clone... 3 days, I'm ready to give up. ANY help would be amazing.

**Comment by markvl91** [comment]
You're much better off asking these questions in the [PokemonGo-Map repository](https://github.com/AHAAAAAAA/PokemonGo-Map/). 

Anyway, I'll try my best helping. Firstly, you're not exactly clear on this, but I'm assuming you have already managed to get a normal server deployed on Heroku through the button in the readme. 
You should be able to add more arguments through the EXTRA_ARGS configuration variable accessed through your Dyno > Settings > Reveal Config Vars. There you can add the EXTRA_ARGS config var and enter any arguments you want. In your case that would be --num-threads XX and --scan-delay XX.

**Comment by PaleHaunt** [comment]
Yes, I do have a server running and working on Heroku. Will that automatically deploy if I do that? I did make changes like this, but it didn't seem to speed it up.
