### ISSUE TITLE
Share server

### ISSUE THREAD

**Issue by marvinmira** [istornz/iPokeGo#105]
Will someone share there server with me ! 

I can't get it running

**Comment by miggs97** [comment]
So I also struggled to get the server working but then I found [localtunnel](https://localtunnel.github.io/www/); so now all I do is run the [Pokemon-Go Map](https://github.com/AHAAAAAAA/PokemonGo-Map), and from there `lt --port 5000` and whatever url is generated in the terminal I enter that into the server in the settings menu. This is a great solution and as of now things are running smoothly.

**Comment by marvinmira** [comment]
@miggs97 Yeah but you mist leave your pc on right ?

**Comment by miggs97** [comment]
Yeah that's the one caveat; you have to leave the server and localtunnel running on your computer.

**Comment by remy-poirier** [comment]
Yes you have to run a local tunnel, you can also use ngrok (really easy to install), and once in ngrok terminal, simply type ngrok http 5000 and you will have the ngrok url

**Comment by marvinmira** [comment]
Maybe i can run a server with the ngrok on it so it will always be posible to locate pokemons ! 

I saw it was really easy to install it so i will work on it! 

Thanks for the information !

**Comment by Psykotik** [comment]
As a solution, you can chose to run the PoGoMap server on a remote server. Few host can be found on web and host your little server for less than a coffee a month (VPS search on google). It should be sufficient for a PoGoMap server. Also you can run the server on a raspberry pi for example, or other nano-computer like this.

Hope this solutions can help you !
