### ISSUE TITLE
Cannot use iPokéGo even on local server.

### ISSUE THREAD

**Issue by vm6ej04** [istornz/iPokeGo#108]
I've got this error in Xcode log

NSErrorFailingURLKey=http://192.168.178.55:5000/raw_data?pokemon=true&pokestops=false&gyms=true, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.}

Any help would be appreciated.. thanks.

**Comment by vm6ej04** [comment]
no I couldn't... interesting..

**Comment by vm6ej04** [comment]
I remember not being able to connect to local server when I was testing an under development website on my mobile.. I just fired up MAMP, port 8888 works though.. not 5000

Here are my command
python runserver.py -a google -u USERNAME -p PASSWORD -l "COORDINATE" -st 50 -sd 5 -t 1 -k API KEY --port 5000

**Comment by markvl91** [comment]
Can you try changing the port in the runserver.py command? Maybe it's just conflicting with something else.

**Comment by vm6ej04** [comment]
Changing the port doesn't make any difference, However I also changed the --host argument to my ip address 192.168.178.55.. now i can access it from my mobile browser.
still nothing showing in iPokéGo, I don't seem to find the log in Xcode anymore, the user interface is really hard to navigate. Where can I find it agian? There might be some new error but I don't know how to toggle the log

**Comment by vm6ej04** [comment]
Hmm...I don't know what happened, but now it worked...

**Comment by markvl91** [comment]
Love it when issues resolve on their own. 👍
