### ISSUE TITLE
Support background app refresh?

### ISSUE THREAD

**Issue by mydonny1986** [istornz/iPokeGo#109]
Can It refresh in the background? Like run in the back ground? I don't see the app in Background App Refresh settings. Otherwise whats the point of push notice on AppleWatch etc.

**Comment by istornz** [comment]
Yes the app work in background task. I don't understand your second question with the Apple Watch (I'm french :p)

**Comment by parrots** [comment]
Background app refresh has a shortest refresh time of ~10 minutes or so. For it to be viable for this app we'd need it <1min. Recommend close the issue as it sadly just won't work for us.

**Comment by mydonny1986** [comment]
So my question is it wouldn't push notification to me when the I turn off my phone screen, then of coz I won't see It on my watch. But I can see the new pokemon show up on my server. Doesn't that mean its not working at the background? Or am I not setting  it right?
