### ISSUE TITLE
Do I have to run the original server?

### ISSUE THREAD

**Issue by axelsly** [istornz/iPokeGo#11]
Interested in making a stand alone iOS app - if anyone wants to help

[RESOLVED] I am a bit confused on how to use this. From what I understand, I have to run the original PoGoMap and then this app connects to localhost 5000 to retrieve info. Is this correct?

Thanks!

**Comment by blackhattristar** [comment]
That is correct.

**Comment by tonygils** [comment]
i don't understand how it works.
I full installed the app, but it doesn't find anything because i didn't fill in the server.
can i only use it at my home server or can i also use it outside?

**Comment by blackhattristar** [comment]
@tonygils You can run the app while away from your home as long as your server is constantly running the code.

**Comment by tonygils** [comment]
tnx,

but what do i need to fill in the server field on my iphone?

**Comment by blackhattristar** [comment]
You need to run [PoGoMaps](https://github.com/AHAAAAAAA/PokemonGo-Map)

**Comment by tonygils** [comment]
yes i allready run that, but what do i need to fill in on my iphone at the server? the api key?

**Comment by philipp-r** [comment]
Just fill in the IP address of your server or domain.

**Comment by tonygils** [comment]
sorry, i'm a noob..
i run pogomaps on my macbook. but i don't use a ip adress, i just enter http://localhost:5000/
if i use that outside, i doesn't work i think?

**Comment by blackhattristar** [comment]
@tonygils You can port forward. [See here](https://forwardhq.com)
