### ISSUE TITLE
Remove location set marker after period of time

### ISSUE THREAD

**Issue by fakemustache12** [istornz/iPokeGo#114]
Setting a new location via this app (tap & hold) adds a green marker to the map. This marker may become invalidated by changing location via another interface or restart of the same server. The marker will continue to show in the same location even after a restart of the app.

You could try to get the current search location from the server but not really doable with multiple search workers running on the same map.

I suggest removing the green marker 1 minute after setting the location.

**Comment by markvl91** [comment]
I don't agree with this. I've set up my server to have a couple of workers dedicated to a specific area, plus the actual server worker which listens to the green dot. As long as I'm not doing something weird myself, the marker will be completely correct, 100% of the time. I believe it depends entirely on how you use your server.

**Comment by fakemustache12** [comment]
I suppose if you only use this app the green dot will always be correct.

I will occasionally switch to the web viewer as it currently shows more data. Any location change made via the web view for the same server does not update the green marker in this app.

**Comment by markvl91** [comment]
Have you raised the same issue at the server repo then? It's the same behavior, the webview doesn't update the scan marker when you use the green dot in this app.

I'll agree that in a perfect world everything would be in sync, and I must say I've been thinking of opening a feature request at the server repo to get the currently scanned location(s) as metadata with the data request. That way we can use that info to redraw the marker at the right location, always.

I hope you can agree with me that simply removing the green dot after a minute isn't the best solution, though.

**Comment by istornz** [comment]
I'm agree with @markvl91 delete the green dot after 1 minute is not a great solution...

**Comment by cristofercruz** [comment]
All good points raised! Feel free to close this issue. as you've mentioned, perhaps when the server stores the current search loc as metadata.

**Comment by fakemustache12** [comment]
Thanks for the feedback
