### ISSUE TITLE
Error when running the new version

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#116]
I get two of these messages in the Gym+CoreDataClass.m file

iPokeGo-master-3/iPokeGo/Gym+CoreDataClass.m:34:23: Implicit conversion loses integer precision: 'NSInteger' (aka 'long') to 'int32_t' (aka 'int')

and this message in the Pokemon+CoreDataClass.m

iPokeGo-master-3/iPokeGo/Pokemon+CoreDataClass.m:21:27: Implicit conversion loses integer precision: 'long _Nullable' to 'int32_t' (aka 'int')

**Comment by istornz** [comment]
These are not errors but warnings. Do not pay attention :)

**Comment by blackhattristar** [comment]
Ok :p

**Comment by blackhattristar** [comment]
@istornz Just curious, what do those warnings mean and will the go away in the future? :)
