### ISSUE TITLE
i can't see any pokemon

### ISSUE THREAD

**Issue by draconiscor** [istornz/iPokeGo#119]
i don't understand which is the correct form that i should write in the "server" space of the app...
I tried: 
- http:// 192.168.0.105
- https:// 192.168.0.105
- http:// 192.168.0.105:5000

but no one works; what am I doing wrong?

**Comment by istornz** [comment]
When you enter "http://192.168.0.105:5000" on safari do you see a map ?

**Comment by draconiscor** [comment]
no, safari can't open any page

**Comment by draconiscor** [comment]
I am a noob to this
How can i lunch server with "-H 0.0.0.0" ?

**Comment by markvl91** [comment]
Have you set up the server downloaded from https://github.com/AHAAAAAAA/PokemonGo-Map?

**Comment by draconiscor** [comment]
Sure, it run in background at this moment

**Comment by markvl91** [comment]
I assume you're able to view the map on your PC then. Is your iPhone connected to the same network as your PC? You could also try setting up a forwarding address through a service like ngrok.com or forwardhq.com, that way you don't have to be connected to the same local network.

**Comment by draconiscor** [comment]
![2](https://cloud.githubusercontent.com/assets/20759048/17279083/b2321e74-576c-11e6-8777-9fea3c2617af.png)
i tried also ngrok.com but when i put the "web interface" parameter in the app it doesn't work too

**Comment by markvl91** [comment]
You can see that it's forwarding to localhost on port 80, while your server runs on localhost port 5000. Can you check if you can change this?

**Comment by draconiscor** [comment]
How can i change this?

**Comment by markvl91** [comment]
You're close, it seems you started ngrok with a command similar to ngrok http _80_, you should start it with ngrok http _5000_. After that you can see the random http://subdomain.ngrok.io domain, just below the line you circled. That's the address you need to enter in the app.

**Comment by draconiscor** [comment]
![definitivo](https://cloud.githubusercontent.com/assets/20759048/17279253/0f7bc4ba-5770-11e6-9666-5658949d2c85.png)
![foto 31-07-16 22 41 31](https://cloud.githubusercontent.com/assets/20759048/17279254/14baf39c-5770-11e6-8394-c668fdb9c6ce.png)

You are GREAT!! now it works! Thank you so much for your patience :D

**Comment by markvl91** [comment]
Enjoy!

**Comment by draconiscor** [comment]
Sure! thank you again
