### ISSUE TITLE
Pokémon Not Showing Up At Current Location

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#12]
Since the app is drawing the information from localhost:5000, it only shows Pokémon at the location the server is running or if you change your location on the localhost:5000 it will change it on the app. Is there any way to load pokémon based on current location In-App?

**Comment by Shugabuga** [comment]
I'm pretty much that is on the to-do list, but correct me if I'm wrong.

**Comment by blackhattristar** [comment]
@Shugabuga You are correct. Sorry, I must've missed that.
