### ISSUE TITLE
Using "Forward" from a local server issue...

### ISSUE THREAD

**Issue by PaleHaunt** [istornz/iPokeGo#120]
I am locally running on my Mac, and using https://forwardhq.com to use on iPhone with iPokeGo. This works well, but it seems some of the setting on iPokeGo can't be used. Do I need to set up what I want on the local script, or is there a way to allow the settings to be "Generic" and give control to iPokeGo for changes on the fly?

Hope this makes sense!

**Comment by markvl91** [comment]
Are you referring to the search location? You can do a long-tap on a location in the map to change that.

**Comment by PaleHaunt** [comment]
No, search is fine. The slide controls like Pokestops, and Gyms. Those seem to default to what the servers is running, and not changeable in the iPokeGo app.

**Comment by istornz** [comment]
Try the latest version of the app, pokestop switch is now working.

**Comment by PaleHaunt** [comment]
thank you!
