### ISSUE TITLE
iPokeGo App and server no longer scanning Pokemon

### ISSUE THREAD

**Issue by Tyalangan** [istornz/iPokeGo#121]
Was working fine the last three days but today it is not displaying any scans and ultimately no Pokemon.

**Comment by markvl91** [comment]
There have been a lot of changes to Niantic's servers the past few days, have you checked https://github.com/AHAAAAAAA/PokemonGo-Map for updates to the server?

**Comment by Tyalangan** [comment]
It was working yesterday at this time. I noticed there was a new version of iPokeGo. Do I have to update to use the app? Because it looked like I needed Cydia to use the new version and I do not want to jailbreak my phone.

**Comment by parrots** [comment]
@Tyalangan the servers started going down down last night, maybe 22 hours ago? See this thread. https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2777

**Comment by Tyalangan** [comment]
@parrots Thanks!
