### ISSUE TITLE
I have built this as a swift version as well.

### ISSUE THREAD

**Issue by brntphish** [istornz/iPokeGo#126]
Does someone wanna enlighten me as to where the data is coming from now? I was previously cramping pokevision's XHR's to get the needed data to do a spiral scan.

https://m.facebook.com/story.php?story_fbid=1061613040574683&id=100001779903579&comment_id=1061748810561106&notif_t=feed_comment&notif_id=1469972088409686&ref=m_notif

**Comment by parrots** [comment]
Data is coming from privately ran servers of https://github.com/AHAAAAAAA/PokemonGo-Map, not a single public source.
