### ISSUE TITLE
Request: Prevent a snapback to current location when scanning another area

### ISSUE THREAD

**Issue by lighter857** [istornz/iPokeGo#127]
Possible to prevent the application from snapping back to current location or potentially introducing a toggle to enable or disable that snap back. 

Find it hard to move around a map and look at details of a poke as it'll take me back to my current location rather quickly. 

I have multiple users setup so I scan a very large area

**Comment by parrots** [comment]
@lighter857 Are you running the latest version from source, or did you install the IPA? This should be fixed with the latest codebase, but it isn't in the binary yet.

**Comment by lighter857** [comment]
Used the IPA. 

Awesome if change is in the code. I can try and compile. 

Any idea when IPA from new code will be posted?

**Comment by parrots** [comment]
Pinging @istornz to answer that question. 2.0 shipped with a few bugs after some huge changes, but they've all been squished today. I'd hope we'll see a 2.0.1 shortly, but he makes that call.

**Comment by istornz** [comment]
@lighter857 Release v2.0.1 is coming today.

**Comment by istornz** [comment]
v2.0.1 is now out

**Comment by lighter857** [comment]
Thank you @istornz !!!
