### ISSUE TITLE
Using the new version. Don't see the notifications. What am i missing.

### ISSUE THREAD

**Issue by mtelaprolu** [istornz/iPokeGo#128]
Selected all the pokemon in favorite pokemon list. Notifications->favorite norification-> ON

Don't see any notification. What am i missing??

**Comment by mtelaprolu** [comment]
And I used version 2.0 IPA

**Comment by parrots** [comment]
The backgrounding in 2.0 was terminated by iOS more often than we'd like, which meant that notifications would stop. We've worked around the system limitations since the release of 2.0, and the next release will be even more reliable in the background.

**Comment by mtelaprolu** [comment]
I don't see the notifications even with the app running on my screen.

**Comment by istornz** [comment]
Try with the latest release v2.0.1.

**Comment by mtelaprolu** [comment]
it works with v2.0.1 . Thanks.
