### ISSUE TITLE
Pokémon Disappearing Timer

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#13]
It's not an issue but it would be nice if we could view a countdown of minutes and seconds for when the Pokémon is going to disappear.

Thanks!

**Comment by philipp-r** [comment]
Something like this would be cool: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1677#issuecomment-234748246

**Comment by istornz** [comment]
Now available.
Thx to @evshade

**Comment by blackhattristar** [comment]
@istornz Much appreciated!
