### ISSUE TITLE
I only installed the ipa file. Which server ip should I put in the settings? Thanks.

### ISSUE THREAD

**Issue by elffish** [istornz/iPokeGo#130]

**Comment by draconiscor** [comment]
You should use your ip. If you don't know which is you can see it using: run > cmd > ipconfig, or here  [ http://bit.ly/2aweVR1](url)
Then write it in the server space: http://x.y.z.k:5000
If it doesn't work use ngrok.exe

**Comment by Zegorax** [comment]
In addition to what @draconiscor said, you need to use the server-side here : https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop

**Comment by draconiscor** [comment]
@Zegorax which is the difference between this link [https://github.com/AHAAAAAAA/PokemonGo-Map](url) and yours?

**Comment by imEduardoBritto** [comment]
I have a sever running on heroku, it was running well before PokemonGo 1.1.0 update after that i can't login to PTC account i used to run the server, i was searching about and look like niantic close the access to the api, sites like pokevision are down too, i think every body is getting this issues now but they don'y noticed that and are getting a headache with their server no showing data...
