### ISSUE TITLE
Pokemon appeared as Gym

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#131]
Has anybody else experienced this issue? I just noticed it for the first time. 

A Pokemon appeared as a gym and then the image disappeared but the timer stayed there. I provided images. 

![image](https://cloud.githubusercontent.com/assets/13209070/17286120/2c6e093c-577c-11e6-90be-1a55ccb2a104.jpeg)
![image](https://cloud.githubusercontent.com/assets/13209070/17286122/2c961260-577c-11e6-87e8-3f72d8bcdba9.jpeg)

**Comment by istornz** [comment]
Are you using the IPA version of the app ?

**Comment by blackhattristar** [comment]
No

**Comment by istornz** [comment]
@blackhattristar Can you test with the latest version of the project plz ?

**Comment by blackhattristar** [comment]
@istornz Version 2.0.1 or should I test the master?

**Comment by istornz** [comment]
Test the master
