### ISSUE TITLE
Pokemon not showing on reopening of app

### ISSUE THREAD

**Issue by andykemp** [istornz/iPokeGo#132]
When I go away from the app and return, there are no pokemon showing.  Going into settings and switching show pokemon off and on again brings them back.  Maybe becuase I'm on iOS10... Any thoughts?

**Comment by istornz** [comment]
Are you using V2.0 IPA ?

**Comment by andykemp** [comment]
I'm using the xcodeproj file I downloaded this morning, which I think v2.
