### ISSUE TITLE
[BUG] Pokemon are not displayed on the IPA, need update

### ISSUE THREAD

**Issue by EiTeR94** [istornz/iPokeGo#136]
Pokemon are not displayed on the iOS appli, i forwarded correctly the port etc, on my PC , it's working i can see pokemons with my IP forwarded, but not on my iphone.
I entered the correct adresse on server adress

**Comment by andykemp** [comment]
If you switch off the Pokemon slider in options and turn it back on do they show?  This is what I'm seeing...

**Comment by EiTeR94** [comment]
Same issue, i can see only on my PC :/

**Comment by EiTeR94** [comment]
I tried to reinstall the IPA, same issue :/ pokemon are displayed on my PC but not on my phone, so the appli is useless :( dunno why i can't make it work

**Comment by markvl91** [comment]
Can you view the map in Safari on your iPhone when you visit the same URL?

**Comment by EiTeR94** [comment]
yes i can see the map and the pokemon, but the position is my home, not my phone location like with the application

**Comment by markvl91** [comment]
Your server is probably just scanning at your home location. Do a long press on the map in the application to start scanning around that location, a green indicator will appear you're scanning there now.

**Comment by EiTeR94** [comment]
on my PC i can see far pokemon from my home position, and on the phone i can't see anything.
I've try with the green indicator to scan arround the green indicator and i still can't see the pokemon.
Is it an iOS 10 issue maybe?

**Comment by EiTeR94** [comment]
It's seems the IPA doesnt work, i try on my ipad, another iphone and i got the same issue.

**Comment by EiTeR94** [comment]
application only work with ngrok, so his utility is useless, cause you can just copy past the ngrok url on your safari and see the pokemon...

**Comment by istornz** [comment]
v2.0.1 is now out plz check with this version

**Comment by EiTeR94** [comment]
Cydia impactor say service not available cause of maintenance activities...
I'll try later

**Comment by Bart274** [comment]
@istornz I'm running v2.0.1 on my iPhone 5c running iOS 10 public beta 2, but I still don't see any pokemon, while I do see them in Safari...

**Comment by istornz** [comment]
Please download the latest version of server and iPokeGO, and open an another issue if the problem persists ;)
(I close the issue to alleviate some outdated issue 👍 )
