### ISSUE TITLE
Scale of assets [Question]

### ISSUE THREAD

**Issue by fraannk** [istornz/iPokeGo#138]
Previously I could change the scale of the icons on the map by changing/removing the "*1.5" scale. I like them a little bit smaller, and since the code has been refactored, I can't figure out where to change the scale. Where has this code section moved to?

**Comment by istornz** [comment]
You can do it by editing the frame of the view in : 

- PokeStopAnnotationView.m
- PokemonAnnotationView.m
- GymAnnotationView.m

Just add or edit : "self.frame = CGRectMake(0, 0, 10, 10);" in the initWithAnnotation func

**Comment by fraannk** [comment]
There it was! Thank you! Totally missed the "Views" folder. :)
