### ISSUE TITLE
I can´t compile the project myself. It keeps stuck at compiling 2 of 2 storyboard

### ISSUE THREAD

**Issue by zippoking** [istornz/iPokeGo#139]
Hi there,

first of all: great app and project! I love it.

To always have the latest version i thought i start compiling it by myself.
I am running Mac OS El capitan 10.11.2 with XCode 7 as a **vmware**.

When i load the project into xcode, i change the bundle identifier and the team.
Finally i click on the play button to build the app on my iphone.
It keeps stuck at compiling 2 of 2 storyboard files.

See picture:
[Stuck at compiling](https://s31.postimg.org/hwa26nccb/Stuck_at_compiling_storyboard_files.png)

Does this have anything to do with running Mac as a vmware?

Thanks in advance.
Best regards
Zippoking

**Comment by istornz** [comment]
Hum... Try to clean the project with **CMD + SHIFT + K**

**Comment by zippoking** [comment]
Thanks for the quick reply, Unfortunately it is not working, even after cleaning the project.

Still stuck at compiling 2 of 2 storyboard files.....

Damn, so close.....I believe its because i am running mac as a vmware..

**Comment by istornz** [comment]
Try to install the app with Impactor : https://github.com/istornz/iPokeGo/releases/tag/v2.0.1

**Comment by zippoking** [comment]
I used impactor for the older version, but as i said, i wanted to compile always the latest version by myself,
Anyhow i got it working: I have now os x 10.11.5 fresh installation as a vmware. I can use xcode 8 beta 4 now and it runs very smooth. Compiling your project took only a few seconds!

Thanks you very much for your help!
This can be closed now.
