### ISSUE TITLE
Block the screenview, is it possible?

### ISSUE THREAD

**Issue by draconiscor** [istornz/iPokeGo#140]
Great job with this app but i have a question.
Is there a way to block the screenview on a position of my choice? Because when i want to see a different part of the map it returns, after a few seconds, at the positions of my gps blue circle. 
This is a bit tiresome, specially when i want to scan different areas from mine.

**Comment by istornz** [comment]
I'm working on it

**Comment by istornz** [comment]
With the latest version this issue is fixed. I'm working on keep map position at startup.

**Comment by draconiscor** [comment]
I installed the app yesterday. I have to install a new version to prevent this issue?

**Comment by istornz** [comment]
Do you have installed the app by the IPA file ?

**Comment by draconiscor** [comment]
yes i do

**Comment by istornz** [comment]
Check the new release v2.0.1

**Comment by draconiscor** [comment]
ok! I have to use Impactor to update the app? In the same way that i install it the first time?

**Comment by istornz** [comment]
You have to delete the old version and use again Impactor :)

**Comment by draconiscor** [comment]
Thank you very much! :D

**Comment by draconiscor** [comment]
i have installed the version at this link [https://github.com/istornz/iPokeGo](url) but the issue already persist :(

**Comment by draconiscor** [comment]
i've found it, thanks!
