### ISSUE TITLE
Time Issues

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#145]
The time/timer seem to be having some real issues. Now they are showing up as distance instead of time. Take a look:

![img_5474](https://cloud.githubusercontent.com/assets/13209070/17301435/dd7b456a-57cb-11e6-9f37-8d2bb3d429fb.PNG)
![img_5473](https://cloud.githubusercontent.com/assets/13209070/17301436/dd90f8ba-57cb-11e6-8fd8-11abef119b64.PNG)

**Comment by parrots** [comment]
This should be fixed in PR #146

**Comment by blackhattristar** [comment]
@parrots Seems to work now thanks to your changes. I'll keep an eye on it. Any idea how I can get rid of this annoying app termination due to memory usage? :/

**Comment by blackhattristar** [comment]
I saw this little guy just sitting around with an odd timer above his head...

![img_5475](https://cloud.githubusercontent.com/assets/13209070/17302109/7df07666-57cf-11e6-9192-4ed802c7ae49.PNG)

**Comment by blackhattristar** [comment]
Now more than one have no time above them but rather just a line...

![img_5477](https://cloud.githubusercontent.com/assets/13209070/17302874/17346c76-57d3-11e6-846b-330366a34726.PNG)
