### ISSUE TITLE
Issue: No Pokemon displaying

### ISSUE THREAD

**Issue by thepog1** [istornz/iPokeGo#148]
Afternoon!
My server is running smoothly running 30 accounts around my area. Showing fine on my PC and Safari for iOS but nothing via the app. Any ideas?

Thanks

**Comment by EiTeR94** [comment]
try the newest version it's fixed .
https://github.com/istornz/iPokeGo/issues/136

**Comment by thepog1** [comment]
I am assuming the newest version is not the one in releases? It that's so, ill need to hold off as I cannot compile my own on windows (please correct me if i am being an idiot).

Thanks for the reply.

**Comment by EiTeR94** [comment]
The last release is 2.0.1.

I can't install it cause cydia impactor give me an error as service is not available du to a maintenance.

**Comment by thepog1** [comment]
are we referring to iPokeGo/Releases/V2.0 (current)/iPokeGo2_current_version.ipa ? As this is the latest i could find without compiling a new one. I installed this aprox. 1 hours ago and this was last updated yesterday?

Thanks

**Comment by EiTeR94** [comment]
https://github.com/istornz/iPokeGo/releases

**Comment by thepog1** [comment]
<3 sorted. Thanks a lot bud!
