### ISSUE TITLE
Map keeps jumping back to the blue location marker

### ISSUE THREAD

**Issue by kevdotcom** [istornz/iPokeGo#149]
Whenever I move the map to view a different area, the map jumps back to my location after 1-2 seconds.

(Also: Does this start it's own search thread? It doesn't seem to interfere with the scan on the website.)

**Comment by draconiscor** [comment]
I report the same problem, you can read here #140

**Comment by kevdotcom** [comment]
Oh I didn't see that... 

I know this doesn't belong here, but is there a discord or something for this project? I have some minor questions and don't know where to ask.

**Comment by lighter857** [comment]
This should be fixed 2.0.1...
What version are you running?

**Comment by draconiscor** [comment]
@lighter857 where can we find version 2.0.1?

**Comment by istornz** [comment]
@draconiscor [**Here**](https://github.com/istornz/iPokeGo/releases/tag/v2.0.1) :)

**Comment by draconiscor** [comment]
oh thanks @istornz ! :D

**Comment by kevdotcom** [comment]
@istornz Can you tell me how this interacts with the server? Does it start another search thread?

**Comment by lighter857** [comment]
No this does not open a new search thread. This will show you the current searcher based on the server address and port you configure.

**Comment by kevdotcom** [comment]
When I tap and hold in the app, it starts searching at this location but if I connect through the website, it's still searching at the old location... How do you explain this then?

**Comment by blackhattristar** [comment]
This is still happening in version 2.0.1 :(

**Comment by lighter857** [comment]
Ok there's 2 different things here. 

@blackhattristar it should be fixed I am running 2.0.1 and not having the issue. Try deleting the app and the certificate and install from scratch (though I didn't have to do that)

@kevdotcom just because you open in to 2 different places so any mean you're creating a second search thread as you most likely are using one login. 

I have 5 users running and I use on one for both web and app. It will not run a 6th instance. It just moves the location of search.

**Comment by blackhattristar** [comment]
@kevdotcom @lighter857 @draconiscor @istornz I removed `[self checkGPS];` from `viewWillAppear` and it no longer jumps back to the user location blue marker. Hope this helps!

**Comment by draconiscor** [comment]
@blackhattristar in the 2.0.1 release there isn't the issue, i checked yesterday

**Comment by blackhattristar** [comment]
@draconiscor I just downloaded 2.0.1 again and it still jumps back to the user location every time after closing the Settings menu. It can be kind of a nuisance.

**Comment by draconiscor** [comment]
ok, only one last question, because i committed the same error yesterday, did you download "iPokeGo2_v2.0.1.ipa.ipa" file or "Source code (zip)" folder?

**Comment by blackhattristar** [comment]
Source code.

**Comment by draconiscor** [comment]
ok! the error is that one! They have the same dimension but the only that you have to download is "iPokeGo2_v2.0.1.ipa.ipa". Download it, install and enjoy! :D
