### ISSUE TITLE
[Feature Request] Show scanned areas toggle

### ISSUE THREAD

**Issue by swemoney** [istornz/iPokeGo#150]
I'd love a way to toggle the "scanned areas" like the web app has. It would also be even more amazing if we were able to improve upon it on the web app by not drawing each individual circle and only drawing the outer border of a area and lightly shading the whole inside. this could also be an option as I'm sure people would still like to see each circle drawn as well.

**Comment by nedaszilinskas** [comment]
+1

Would be great feature! And I agree about the radius border instead of the circles!

**Comment by istornz** [comment]
Now added for Pogom server.
