### ISSUE TITLE
Is it possible to change default Apple Map to Google Maps?

### ISSUE THREAD

**Issue by mantergotest** [istornz/iPokeGo#153]
My city is not detailed in Apple Maps, so it is impossible to find out any pokemon location. Is it possible to change default Apple Map to Google Maps?

**Comment by jaredmfier** [comment]
+1, google maps are much more detailed/accurate in my location as well.

**Comment by hoidaan** [comment]
+1

**Comment by kevdotcom** [comment]
+1

**Comment by MrAwesomers** [comment]
Is it not using google maps already? Why did we need to enter a google maps api key in order to use the scanner?

**Comment by istornz** [comment]
Hum it would be great but we use Apple Maps because it's native and more fast.
To change the map, we all need to review the app :/
