### ISSUE TITLE
App Termination

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#155]
I got this error while letting the app run in Xcode.

 Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x16301cf40> was mutated while being enumerated.'

This is what gets highlighted once the app terminates. 

NSArray *gymsToRemove = [annotations filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"self isKindOfClass: %@ AND self.gymID IN %@" argumentArray:@[[GymAnnotation class], self.annotationsGymsToDelete]]];

That's under the - (void)controllerDidChangeContent:(NSFetchedResultsController *)controller section

**Comment by istornz** [comment]
Do you have always this error ?

**Comment by istornz** [comment]
I close this thread.
Please open a new one if you have the same bug.
