### ISSUE TITLE
iPokeGo2_current_version.ipa BETA Expired ? 

### ISSUE THREAD

**Issue by magoo89** [istornz/iPokeGo#156]
i have installed iPokeGo2_current_version.ipa but the application say´s when i start the App the Beta is expired

**Comment by draconiscor** [comment]
here the latest release: https://github.com/istornz/iPokeGo/releases

**Comment by hoidaan** [comment]
Same issue here when I install it via ipa installer, but when I do it via the computer with cydia impactor it does work.. Any idea why that is?

**Comment by istornz** [comment]
Impactor resign the IPA to fit with your account

**Comment by hoidaan** [comment]
Of course thanks! Awesome app btw:D

**Comment by magoo89** [comment]
yes thank you ! :)
