### ISSUE TITLE
Follow my location

### ISSUE THREAD

**Issue by DmitryMironenko** [istornz/iPokeGo#157]
Is it possible to switch search location to follow my current location like in browser version? I setup a green point to search neighbor location and don't know how remove it and return to follow my location.

**Comment by tchit** [comment]
Same here, is there a way to simply remove the green point? 

Thanks, amazing app!

**Comment by istornz** [comment]
@tchit Not for the moment but "follow location" is on the road map !

**Comment by dmunozfer** [comment]
Implemented in PR #214
