### ISSUE TITLE
My map is empty

### ISSUE THREAD

**Issue by inkkinker** [istornz/iPokeGo#160]
I installed the app on my IPhone 5s and I put the server in the settings and on now there is nothing to see on the map?

Does anyone have an idea what my problem could be ?

**Comment by jerry317** [comment]
Me too.

**Comment by blackhattristar** [comment]
@inkkinker @jerry317 Are you using a cloud server to access the Pokémon GO api?

**Comment by jerry317** [comment]
@blackhattristar yes, I'm using Linode.

**Comment by blackhattristar** [comment]
@jerry317 That is probably the problem. Pokémon shut down access to their api via "most" cloud servers.

**Comment by blackhattristar** [comment]
@jerry317 If that is not the problem, I would be very surprised.

**Comment by alexsosaaa** [comment]
I'm also having the same problem but I don't get the whole cloud server issue

**Comment by blackhattristar** [comment]
@alexsosaaa Are you using a cloud server?

**Comment by alexsosaaa** [comment]
No

**Comment by inkkinker** [comment]
I run the map over an Ubuntu vServer

**Comment by draconiscor** [comment]
Try to read #119 , i had the same problem and now with that instructions it has been solved

**Comment by Bart274** [comment]
it doesn't work for me either, I can see the map but I never get results.
the map works great in a browser though

**Comment by istornz** [comment]
@Bart274 Do you have again the bug ? (if yes, please open a new issue 👍 )
