### ISSUE TITLE
[Enhancement] Notifications based on distance

### ISSUE THREAD

**Issue by Absentee23** [istornz/iPokeGo#163]
Many people are using the map system with multiple scanners over a large area (ie the hex hive), and the notifications system in iPokeGo is great! However I'd love to be able to tune the app to only alert me of a pokemon within a certain distance of my current location.

The _majority_ of the alerts I get are for pokemon too far away for me to get at the moment, but I don't want to have to kill and then restart scanners when I _do_ head to those locations. I also share the scanner with friends and have scanners in their vicinity, but do not want to receive alerts for pokemon that spawn miles away.

**Since a pokemon's distance from you is already being calculated, I think a nice solution to this would be to set a distance in the notification settings for notifications to be limited to** (defaulting to infinite.) This would then only notify when something spawns within that distance of your current location. This being changeable on the fly in the app would be much more convenient than remoting in and finding specific scanner processes to kill.

**Comment by partydragen** [comment]
@Absentee23 where are you? Have u dropped Spigot, Discord and Playerservers?

V2 have bigs bugs so i using V1 again

**Comment by kevdotcom** [comment]
It would also be pretty handy to show the current distance to the Pokemon inside the Notification. 

Like:
iPokeGo
Magmar spawned 332m away from you.

**Comment by istornz** [comment]
Now added. I close the ticket :)
