### ISSUE TITLE
Pokémon Not Appearing

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#165]
I'm not sure what the cause if this issue is but if I scan somewhere on the map, Pokémon don't usually appear until I open Settings and then close Settings. Once I do that, sometimes the Pokémon will appear. It's almost like the map isn't refreshing until you force refresh it by going to another view controller (like Settings) or closing and opening the app.

Any ideas what this could be? It started happening within the most recent versions.

**Comment by SethG911** [comment]
Same as this issue? #210
