### ISSUE TITLE
Missing IPA file?

### ISSUE THREAD

**Issue by iPenguin67** [istornz/iPokeGo#168]
The instructions for installing the iOS port say to download the most recent IPA file, but the master doesn't seem to include an IPA file. The Releases folder now redirects to a 404.

**Comment by DrKinSlayeR** [comment]
https://github.com/istornz/iPokeGo/releases :D

**Comment by iPenguin67** [comment]
Thanks! Didn't notice that before. 

One more question while I'm at it I guess. I got the app installed, and entered what I think is a server address found here: http://www.mon-ip.com/ (the "Son Nom d'hôte associé" -- since the instructions said to use that link if you don't have a local server). I'm not sure if that was right, but I don't see any Pokemon in my local area when I launch the app.

**Comment by istornz** [comment]
You have to set "Votre adresse IP est :" xx.xx.xx.xx. 
So the complete URL should be : http://xx.xx.xx.xx:5000
