### ISSUE TITLE
Notifications push

### ISSUE THREAD

**Issue by DrKinSlayeR** [istornz/iPokeGo#169]
Hi sorry for ou english. 

I don't have notification push on my iPhone 6+ iOS 10. How I can activate them ? All notifications settings are enable.

**Comment by DrKinSlayeR** [comment]
HELP ? :D

**Comment by AndreasEnemyr** [comment]
It can be with iOS 10, but im not sure

**Comment by hoidaan** [comment]
Did you enabled the "run in background" setting as well in iPokeGo?

**Comment by DrKinSlayeR** [comment]
Yeah, all settings are enable on iPhone settings and "run in background" too.

**Comment by daproject85** [comment]
no push notificatios, only in app notifications

**Comment by DrKinSlayeR** [comment]
No no it's fine after a new installation, I've got the push notifications ! 

[http://www.hostingpics.net/viewer.php?id=713868IMG1190.png](url)
