### ISSUE TITLE
Tug-O-War

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#170]
Is there any way to not play tug-o-war with the map when using it between a few people in different locations? My buddy is in Oregon and I'm in Cali and when we scan the map, I notice the map scan location changes for both of us, so it's like we're playing tug-o-war with each other on who gets to scan a location. Any help would be greatly appreciated!

**Comment by MysticalOS** [comment]
Honestly you shouldn't both use the same server. that's not how it's really meant to work. unless you're both together then maybe. but in which case still probably only need one of you running it. if you're going to share don't do it at same time. it cannot scan two diff locations at once.

**Comment by blackhattristar** [comment]
@MysticalOS Is it possible to make a version that can scan multiple locations? I'm assuming that's what PokeVision used to do, right?

**Comment by MysticalOS** [comment]
This app is just a front end (GUI) for https://github.com/AHAAAAAAA/PokemonGo-Map/ so it only really does what it does. that supports multiple accounts but for scanning same location. if you want to scan two diff locations same time you really just should be running two different go map servers.

**Comment by swemoney** [comment]
You'd have to use MySQL as your database for thread safety and then just start multiple instances of the server with different port numbers but the same database.

**Comment by kevdotcom** [comment]
That would make you get notifications from all locations...

**Comment by istornz** [comment]
Now you can use Pogom server to scan multiple location.
I close
