### ISSUE TITLE
Scanning Activity Indicator

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#171]
This is an enhancement suggestion. Is there any way to add an activity indicator that lets you know the scan is in progress? Sometimes it takes a while to load Pokémon and you don't know if it's working or doing anything. This would be really helpful and ease the mind if you could know it's scanning. :)

**Comment by istornz** [comment]
Good enhancement !

**Comment by istornz** [comment]
Added for pogom server

**Comment by blackhattristar** [comment]
@istornz Is it available for pogom server only?
