### ISSUE TITLE
Empty map

### ISSUE THREAD

**Issue by iPenguin67** [istornz/iPokeGo#175]
Bear with me, as my knowledge of servers is pretty basic, and I am pretty sure my empty map is due to entering the server incorrectly. 

The instructions for installing read:
"On settings, please enter the address of your server.

Warning : "localhost:5000" or "127.0.0.1:5000" are hardware address so it will not work !

To find your address look at this : http://bit.ly/2aweVR1 (if you have a local server) and http://bit.ly/1dWVBmR (if you want to remote server)."

Both of those addresses returned my IP address (which I thought was distinct from a server). When I entered "http://xxx.xx.xxx.xx:5000" into the server field, nothing shows up. However, I'm not sure why I am entering my IP there at all -- is there not a main server from Ahmed's original project that this app taps into? When I ran his Python script in my Terminal, I did not have to specify a server. 

Furthermore, if I am using some kind of local server, then how is my phone going to be able to run this search when I am out and about (which is the main reason for even having an iOS app for this)?

Any thoughts on what I'm doing wrong here? Or am I misconceptualizing this entirely?

**Comment by istornz** [comment]
Did you open port 5000 ? (only if you want remote server)

**Comment by iPenguin67** [comment]
I'm not sure. From what I can tell, Macs typically allow incoming connections on an application basis, which isn't helpful here. Is there a way I can manually do this?

**Comment by istornz** [comment]
@iPenguin67 When you enter "http://xxx.xx.xxx.xx:5000" in Safari do you have the map ?

**Comment by iPenguin67** [comment]
Nothing seems to happen when I enter that -- it just loads for a while. I get the map when I use "localhost:5000" while the Python script is running though.

**Comment by rohapa** [comment]
API Changed
https://www.reddit.com/r/pokemongodev/comments/4w0jum/all_ptcgoogle_logins_failing_from_api/

**Comment by iPenguin67** [comment]
So is that endgame for these apps then?

**Comment by siideffect** [comment]
@iPenguin67 just let Devs do their work. For now, i can confirm map is not showing any pokemon due to api change as already said. Just wait and refer to https://github.com/AHAAAAAAA/PokemonGo-Map for updates.

**Comment by iPenguin67** [comment]
OK, ultimately though even before the API was changed (aka last night), I was unable to pull up any results on the iOS app. I guess my questions boil down to:
1. Is http://xxx.xx.xxx.xx:5000 the correct address to enter into the "Server" field?
2. If so, how do you manually open port 5000 on a Mac? 
3. Assuming both of the above are done, does this allow the iOS app to search for Pokemon when you are actually on the go and not just at home on the same network as your computer?

**Comment by robiningelbrecht** [comment]
POkemon GO api has changed, you will have to wait until this issue is fixed https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3406
