### ISSUE TITLE
GoRadar working

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#177]
@istornz Can you check out this app GoRadar on the iOS app store or visit https://map.goradar.io and tell me how on earth they are doing this?

If you test out the iOS app you'll see that you don't even have to long press on the map to scan. You just move the map around and loads of Pokémon appear on the map almost instantly. 

I'm really scratching my brain over this.

**Comment by Bizadon** [comment]
I think, that is beacause they have a db storage and a lot of clients use it, so it just loading pokemons on previous requests.

**Comment by blackhattristar** [comment]
@Bizadon If that's true, then I feel like they know more than just where you've scanned before.

**Comment by Bizadon** [comment]
@blackhattristar Yep, they know where are you live and work :)

**Comment by WilliamLCobb** [comment]
I don't scan Niantic's servers. I also develop the tweak Poke Go ++ and collect data from there

**Comment by HasanY1989** [comment]
@WilliamLCobb if you do not scan how do you do it ?
iPokeGo is made by istornz which you also integrated with your server. 
Share it to the rest so we also can get our map up and running

**Comment by WilliamLCobb** [comment]
As I said, I collect data from the users of my tweak. While the front ends are the same I'm using my own server. I could release the source but it's not going to offer anyone any benefit. it's also pretty self explanatory. It stores the data sent by tweak users and selects it when queried by app users.

**Comment by HasanY1989** [comment]
@WilliamLCobb so let me understand this correct, stores data from ur tweak (pokomon map made by ahhaaa edited by you) and send it to ur app users.  correct me if im wrong mate

I got my own server as well, and since you were kind enough to share it, then yes, please do send ur source privately or openly, it will help me better to understand ty :P :+1:

**Comment by Brian-Graham** [comment]
@HasanY1989 users submit the locations of the pokemon, that's why it will be of no use to anyone. You could run what he's using but if you have no users (actual people) to submit pokemon, it won't do anything.

**Comment by HasanY1989** [comment]
@Brian-Graham he must have a lot of users since  tested it out and it seems to come with time and everything.

I got 200+ users atm (most likely i was just testing to se ehow much my server could handle)
