### ISSUE TITLE
Cant change location and street names

### ISSUE THREAD

**Issue by Bizadon** [istornz/iPokeGo#178]
As in #88 have the same problem, map doesnt change location. If I rightly understood - to change location I need to tap search button and change location, but when I tap on it - nothing happens. Just built the new version of ipokego few minutes ago and using the latest version of master branch of pokemon go map.

The second problem is that in satellite map style - there is no street names, is that maybe only with me?

**Comment by istornz** [comment]
To change location you have to long press on the map to place the scan annotation
