### ISSUE TITLE
server

### ISSUE THREAD

**Issue by ddavyy** [istornz/iPokeGo#179]
Hello, great application, but I have a problem no Pokémon appears I think this is due to the server. 

I can not configure it, I'm trying several places but it does not work on my iPhone 6s.

When I check the address of my Port it changes all the time so I do not understand exactly how to configure it to work. 

I think a written tutorial or video would be the top. 

Thank you in advance for answers.

**Comment by blackhattristar** [comment]
@ddavyy Pokémon GO changed their API and dev's are actively working on a fix. See https://twitter.com/pkmngodev | https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d65hrv5 | https://www.reddit.com/live/xdkgkncepvcq/

**Comment by istornz** [comment]
Now fixed with the latest version of the server. I close
