### ISSUE TITLE
Configurable "common"

### ISSUE THREAD

**Issue by gerwitz** [istornz/iPokeGo#18]
In my area (Amsterdam, The Netherlands) there are some Pokémon that are common here but might be interesting elsewhere. (E.g. Magikarp and Psyduck)

I'd love to be able to configure the common list for filtering these out.

**Comment by areteCocoa** [comment]
I've thought about ways to make multiple configurable lists, not just common.

**Comment by mydonny1986** [comment]
You can just replace the pokemon photo with a blank png then they won't show up on the map, just a work around

**Comment by istornz** [comment]
This functionality is now working. The way to custom your list is planned for soon :)
