### ISSUE TITLE
What's going to happen to iPokeGo?

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#180]
Since Ahmed Almutawa has shut down the [Pokémon Go Map](https://github.com/AHAAAAAAA/PokemonGo-Map), what will happen to iPokeGo?

**Comment by HasanY1989** [comment]
We can use what we have and wait for the API fix?
To be honest i lost hope....

**Comment by blackhattristar** [comment]
@HasanY1989 "Use what we have"? What would that be? My map doesn't show Pokémon, PokéStops or Gyms so what I have is useless. I'm sure there are devs out there that are still going to crack the API (again) but unfortunately it won't be coming from that awesome repo.

**Comment by HasanY1989** [comment]
I know, but the current stable vi have, cant we just implent the api thing? im not a coder my self mate
