### ISSUE TITLE
Confused..

### ISSUE THREAD

**Issue by HasanY1989** [istornz/iPokeGo#181]
Since the other topic was closed...
Pokomon go map is shut down, what about this project, it works with the maps... 

My thought is when the API gets fixed, can we edit the current map we have so it works, or is it alot more work todo than just that?

**Comment by blackhattristar** [comment]
Please check this forum for updates on the API fix. [API Updates](https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d65hrv5)

**Comment by HasanY1989** [comment]
@blackhattristar thanks for the answer, but that was not my question and i am already following that. 
please read my questions, and do not close this topic ty :-) 

My question again: How to edit the correct stables we have the the upcomming API fix, is it a small or big issuc ? like re work the code or somthing?

**Comment by MysticalOS** [comment]
Pull from:
https://github.com/crim50n/PokemonGo-Map/tree/develop

Which is clone of the closed repo. make sure develop branch

Then
https://www.reddit.com/r/pokemongodev/comments/4wiuv6/scanners_using_updated_api/d67c7wz

I couldn't get encrypt.dll to work in OS X though. something tells me this current solution is windows only? I'll have to try it on remote server later.
you get map working and this app will work again on it's own.

**Comment by blackhattristar** [comment]
I'm following everything this says to do and it's not working :( Where do I apply the patch code?

**Comment by DrKinSlayeR** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map if you want the latest version with encrypt for OSx and the other OS !

**Comment by blackhattristar** [comment]
@DrKinSlayeR I get `2016-08-06 22:39:33,218 [      MainThread][     runserver][CRITICAL] Please run "grunt build" before starting the server`

Any help would be greatly appreciated!

**Comment by blackhattristar** [comment]
I got it working on my Digital Ocean Droplet! Thanks for the help.
