### ISSUE TITLE
jelastic server

### ISSUE THREAD

**Issue by GabrielAraujo** [istornz/iPokeGo#182]
Hey,

I have deployed the new api Pokemon Go api map to Jelastic..

Do you know if I have to setup any other thing to make it work on the app?

Currently it is crashing when the app try to convert the data received from the server to JSON because it is HTML..

**Comment by istornz** [comment]
Do you use the latest version of PoGo Map ?

**Comment by GabrielAraujo** [comment]
Yes it is working now!
