### ISSUE TITLE
what am i doing wrong?

### ISSUE THREAD

**Issue by HasanY1989** [istornz/iPokeGo#183]
This question for Poko map, not this app, however it works with it. if any one oculd help i apperiate it !
Question:
I have no idea what i'm doing wrong. 
On the easy setup, it gives me this error. 
"Command "python setup.py egg_info" failed with error code 1 in c:\users\haso\appdata\local\temp\pip-build-k4z4cl\pyproj\"
after that i try to do npm install. 
works fine but when i run it, it gives me this error.

Traceback (most recent call last):
"File "runserver.py", line 28, in 
import pgoapi
File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi__init__.py", line 1
SyntaxError: Non-ASCII character '\xf3' in file C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details"

i run ith with cmd line:

C:\Python27\Python.exe runserver.py -a ptc -u user-u use -u user -p pas2 -p pas3 -p pass4 -l "NewYork,America" -st 8 -sd 5 -H 0.0.0.0 -L en -P 69

**Comment by draconiscor** [comment]
have you installed Microsoft Visual C++ Compiler for Python 2.7?

**Comment by HasanY1989** [comment]
Yes i have, i am trying everything xD 
I will later try to uninstall Python delete the map and reinstall it

**Comment by HasanY1989** [comment]
fixed
