### ISSUE TITLE
Change scanning position in realtime?

### ISSUE THREAD

**Issue by GuyNamedMiguel** [istornz/iPokeGo#186]
I'm using ngrok to setup a server on my pc and then connect to it with the app, but it doesn´t change the scanning position to my actual position. The scan just stays where I set the location when I started the server on my pc, and that makes it not usable mobile. Could you make it that when I move with my phone, I can click a scan button and then the scanning position is changed to my current location, just like it is on the PC version of the map?

**Comment by MysticalOS** [comment]
To change location all you do is hold thumb on a location to place a marker, that'll place a green pin on map and redirect server to it.
There currently is no feature to follow YOUR location. the scan button isn't what you think it is. It's a "move to scan pin" button just like other button is 'move to my location' button. It is NOT a scan button.

**Comment by AbelIngrand** [comment]
This is complicated to implement for now as the server part restarts from the scanning from the beginning when you set a new location..
