### ISSUE TITLE
error loading http://localhost:5000/

### ISSUE THREAD

**Issue by geppoapps** [istornz/iPokeGo#19]
after running the command and when checking http://localhost:5000/  it's showing this error! is there anyone who can help with solving this problem?
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by philipp-r** [comment]
see https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1728

**Comment by istornz** [comment]
#26
