### ISSUE TITLE
after notification shown, the pokemon is hidden

### ISSUE THREAD

**Issue by tsuncp** [istornz/iPokeGo#192]
the icon of the pokemon is not shown after press the favorite notification

restart the app, the pokemon icon will be back

**Comment by Jones1337** [comment]
same bug herr

**Comment by hoidaan** [comment]
Me too sometimes

**Comment by markvl91** [comment]
The only case where I can see this happening is if you have 'hide common' turned on, and you get a notification for a common pokemon. I'm working on an update to filter those notifications out.

**Comment by tsuncp** [comment]
Umm. In fact, I dun turn on hide common
I show all the Pokemon and just turn on favourite notification
「Mark van Lagen <notifications@github.com>」在 2016年8月9日 週二，下午8:34 寫道：

**Comment by markvl91** [comment]
I've noticed I sometimes get notifications when a pokemon disappears, causing this to happen. However, this doesn't fit with the pokemon reappearing on your device after a restart. To be honest, I'm stumped, sorry.

Has anyone else been able to replicate this problem?

**Comment by kevdotcom** [comment]
I don't know if it's the same bug, but I have the problem that some Pokemon disappear from the map (inside the app, website is fine) and then sometimes flash in and back out of existence for a brief moment... I'm using the webpage in mobile safari more than iPokeGo at the Moment.

**Comment by istornz** [comment]
Please test with the latest commit 👍

**Comment by Jones1337** [comment]
bug is still alive

**Comment by istornz** [comment]
@markvl91  I'm not able to reproduce this bug too

**Comment by istornz** [comment]
Now fixed with latest commit.
I close (please open a new issue if you found the same bug again).
