### ISSUE TITLE
ngrok server violation due to too many connections

### ISSUE THREAD

**Issue by torres01** [istornz/iPokeGo#193]
it works perfectly fine for about 5-10 min. then the pokemons start to disappear from the app. live map is still working, mobile access is still enabled. testing the ngrok server url in safari brings this error: "too many connections! the tunnel session...has violated the rate-limit policy of 20 connections per minute. please decrease your inbound connection volume or upgrade to a paid plan for additional capacity. "
this really makes the app useless for now, since the server url the live map creates isn't connected to any ngrok account with a paid plan. is there a possibility to fix that?

**Comment by markvl91** [comment]
You should create a free ngrok account, this increases the maximum number of connections per minute to 40.

**Comment by torres01** [comment]
why closed? the problem is not solved
