### ISSUE TITLE
Images missing on favorite and common list

### ISSUE THREAD

**Issue by ChonLee** [istornz/iPokeGo#194]
I can see the lists for the mons and my previous ticks are there, but the images and text on the favorite and common lists are missing.  In the debug log I'm getting...

`iPokeGo[9962:1250076] Could not load the "1.png" image referenced from a nib in the bundle with identifier`

**Comment by diepflanzen** [comment]
got the same error

**Comment by baulie** [comment]
Yes, same problem here. Running on iOS 9.3.4 and latest dev beta iOS10.

**Comment by twoLegsGood** [comment]
Looks like the `pokemoncell` constraints for UIImageView and UILabel on Main.storyboard -> Favorite Scene controller got wiped out.
