### ISSUE TITLE
Possibility to listen 2 port from the same database

### ISSUE THREAD

**Issue by Made123** [istornz/iPokeGo#195]
Hello,
I ran 2 process of scan from my database. One to port A the other to port B.
But in the apps, we can only set one port, like this: http://0.0.0.0:portA
Is it possible to merge the data from 2 port ? maybe like this: http://0.0.0.0:portA:portB
Or add an option.

Respect for your works, your app is really helpful.
Regards,
Made.

**Comment by markvl91** [comment]
This isn't possible, you should set up your server workers so that they both save their data to the same database. This allows data from both workers to show up in the app.

**Comment by Made123** [comment]
Hello,
I tried to launch 2 run process from the same area, then the database pogom.db is created in the same directory, and it works !!

I was afraid about 2 process writing in the same db in the same time.
This is a cool result ^^

Thx so much !
