### ISSUE TITLE
Radius vs server radius

### ISSUE THREAD

**Issue by stephan-v** [istornz/iPokeGo#198]
I was wondering why the radius for the app is a lot smaller than the pokemon radius I am seeing on my server.

Is there any way to increase the radius so I can see more pokemons on my map?

**Comment by MysticalOS** [comment]
pinch zoom? It zooms like any other iOS app.

**Comment by stephan-v** [comment]
@MysticalOS This does not matter here, it's not about seeing a large portion of the map. It's about getting to see more pokemon in a large area of the map. I know how to zoom...

**Comment by istornz** [comment]
@stephan-v I added this functionality for pogom server
