### ISSUE TITLE
Cydia impactor

### ISSUE THREAD

**Issue by PugliesiPc** [istornz/iPokeGo#202]
First of all sorry for my english i am french.
I ´m new on this website, so i ´m maybe on the wrong place to ask that.
I have a problem with the installation:
When i drag the folder "iPokeGo master" to cydia impactor, i enter my login and i got an error message "permission denied"
My iPhone isn't jailbreak.
Can you help me cause i want this it looks cool.

**Comment by PugliesiPc** [comment]
I have Windows

**Comment by dapoldi** [comment]
1; don't try to install a code-branch, install the compiled release; https://github.com/istornz/iPokeGo/releases <--- Download it here.
2: https://github.com/istornz/iPokeGo/wiki/Installing-iPokeGO-with-any-computer-(Windows,-Mac-and-Linux)-easily-! <--- Guide.

**Comment by PugliesiPc** [comment]
Thank you men i ´m going to try
