### ISSUE TITLE
ngrok too many connections

### ISSUE THREAD

**Issue by torres01** [istornz/iPokeGo#204]
after some time the pokemons start to disappear from the app. live map is still working, mobile access is still enabled. testing the ngrok server url in safari brings this error: "too many connections! the tunnel session...has violated the rate-limit policy of 20 connections per minute. please decrease your inbound connection volume or upgrade to a paid plan for additional capacity. "
the server url which the live map creates isn't connected to any ngrok account with a higher rate limit-and can't be right?-. is there a possibility to fix that?

**Comment by markvl91** [comment]
You can register for a free account at ngrok, this increases the limit to 40 connections per minute.

**Comment by torres01** [comment]
yes i know but the app creates the grok url's. its not connected to my account. i run the app on a mac without command lines. so this basically does not work for me

**Comment by markvl91** [comment]
I assume you're using https://github.com/mchristopher/PokemonGo-DesktopMap then. Unfortunately, unless that app adds support for registered ngrok accounts, it's not possible to fix this without setting up a map of your own, without the Electron wrapper app.

I'd suggest raising the issue there and see if they can lend a hand.
