### ISSUE TITLE
Scan Time

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#206]
I've got the map running on a nice fast server but the scan time seems to take forever. Is there any way to speed up the scan process? Even if it misses a Pokémon, I'd rather that than waiting for it to scan for as long as I do. 

Thanks!

**Comment by markvl91** [comment]
Please ask over at https://github.com/pokemongomap/pokemongo-map/issues.

**Comment by blackhattristar** [comment]
I've figured it out! Thanks!
