### ISSUE TITLE
no pokemon show up in favorite and common pokemon list

### ISSUE THREAD

**Issue by chadkoepf** [istornz/iPokeGo#207]
I installed the app through the developer program instead of using the cydia impactor.  The app seems to work okay, but the favorite and common pokemon lists are blank so I'm unable to know which ones I'm turning on and off.  Was this with my installation choice, or is it maybe something with running ios beta?

**Comment by quentinlesceller** [comment]
Same here, app is side loaded with Xcode 8 beta. iPhone is running iOS 10 Beta 5.

**Comment by austexcn** [comment]
same here

installed using xcode 7.3 on an iphone 6s running ios 9.3.4

**Comment by quentinlesceller** [comment]
I also tried with Xcode 8 beta and iOS 9.3.4, same issue.

**Comment by nilz90** [comment]
same here Xcode 8 beta ios 9.3.3

**Comment by markvl91** [comment]
Should be fixed in #208

**Comment by iEtyp** [comment]
Oh come on guys! Enter the project at Xcode >>>>iPokeGo>>>Main.storyboard>>>Main.storyboard(Base) then Favorite Scene>>>Favourite>>>>Table View>>>pokemoncell>>>Content View, and then select "Pokemonimage View" and resize it a little bigger and do this the same with "Pokemon Name".
Viola! Just build and upload again on iDevice:)

**Comment by austexcn** [comment]
@iEtyp haha it's so simple :P
