### ISSUE TITLE
Error: Impossible to make the request

### ISSUE THREAD

**Issue by chaitanya-ramji** [istornz/iPokeGo#21]
The request isn't getting completed and hence no Pokemon is spawning up on the screen. Any idea why I'm running into this issue? My log reads:
`2016-07-25 17:47:48.782925 iPokeGo[3242:1413768] [+] ----- LOAD SAVE DATA
2016-07-25 17:47:48.805505 iPokeGo[3242:1413768] Presenting view controllers on detached view controllers is discouraged <MapViewController: 0x13be084d0>.
2016-07-25 17:47:48.825394 iPokeGo[3242:1413768] [LogMessageLogging] <private>`

**Comment by chaitanya-ramji** [comment]
I changed the server and this issue has disappeared. Pokemon still aren't spawning on the screen. I have tested on a iPhone 6s on iOS 10 beta 3 and an iPhone 6 on iOS 9.3.3.

**Comment by didacus** [comment]
@chaitanya-ramji Where can I find other servers? I am having the same error.

**Comment by chaitanya-ramji** [comment]
@didacus I port forwarded my localhost, it seems to be working.
