### ISSUE TITLE
No Pokémon Showing Up

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#210]
I just downloaded the latest version and everything (in my console) is working fine but there are no Pokémon showing up. Gyms showed up, PokéStops showed up but no Pokémon. When I look at my map on my server, the Pokémon are there but not on the map in the app. Any help would be greatly appreciated! 

Thanks

EDIT: 

It's not until I quit running the app and start running it again that the Pokémon appear.

**Comment by MysticalOS** [comment]
I'm seeing same thing. web app works but This never shows anything. even restarting it several times. Latest source just freshly built. latest map

**Comment by SethG911** [comment]
I am having the same issue upon first opening the app. If I press home, then come back to the app, or close the app and start it again, it seems to fix the issue until the next time I start the app. Using PokemonGo-Map as the server.
