### ISSUE TITLE
How to install pokemon go map on MAC?

### ISSUE THREAD

**Issue by cookieLSX** [istornz/iPokeGo#211]
Hello guys, I was wondering if someone could help me out to install the pokemon go map on a MAC, since the only one video out there so far is for windows. Would really appreciate it as I am trying to make the app on my IOS so that I don't always have to be remoting it from my PC and mobile toggle:)

**Comment by markvl91** [comment]
You should be able to find this info at the PokemonGo-Map repository, not this one.

**Comment by istornz** [comment]
Check this documentation : https://pgm.readthedocs.io/en/develop/basic-install/osx.html
