### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by PugliesiPc** [istornz/iPokeGo#212]
Hi,
It's the french boy again, so with your help guys i succes to have iPokeGo on my iPhone.
But now i need a server and i don't know how to get one.
Please help

**Comment by ddavyy** [comment]
Hello,

It's the same for me except I do know a server via the Mac application but it does not last very long.

So if a charitable soul could give us or we explained how to put a server would be super nice.

Thank you

**Comment by blackhattristar** [comment]
Check out the basic or advanced installation [here](https://pgm.readthedocs.io/en/develop/)

**Comment by ddavyy** [comment]
Thank you for the answer but it does not concern iPokego but PokemonGomap .

In iPokego application ios we are asked a server address and our login and password are those of our apllication Pokemongo I think.

**Comment by istornz** [comment]
@ddavyy Check this doc for mac : https://pgm.readthedocs.io/en/develop/basic-install/osx.html

**Comment by istornz** [comment]
You have to install on your computer the server and after set the ip address in iPokeGO

**Comment by ddavyy** [comment]
Thanks
