### ISSUE TITLE
Not showing Pokemon anymore 12:45

### ISSUE THREAD

**Issue by longDong2x** [istornz/iPokeGo#215]
I'm wondering its been blocked by niantic.

**Comment by blackhattristar** [comment]
@longDong2x I'm still seeing Pokémon.

**Comment by istornz** [comment]
@longDong2x @blackhattristar Yes me too. Are you using a VPS or your computer to run the server ?

**Comment by longDong2x** [comment]
I was using my ipad

**Comment by kevdotcom** [comment]
You need to run https://github.com/PokemonGoMap/PokemonGo-Map and connect to the server in order to use the map.
