### ISSUE TITLE
Not showing Pokemon in Singapore

### ISSUE THREAD

**Issue by lexthefalex** [istornz/iPokeGo#217]
Cant seem to see any pokemon in Singapore and using an ipad. Worked fine for the previous days though

**Comment by istornz** [comment]
Can you see any pokemon in Singapore with the web version ? By accessing url inside Safari

**Comment by thisismohitgupta** [comment]
@lexthefalex your Ip was probably banned

**Comment by istornz** [comment]
Please reopen the issue if you have the problem again.
