### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by tiamat71** [istornz/iPokeGo#219]
hi, 

i made french translation, how can i update your project ?

**Comment by istornz** [comment]
Hello, propose a PR request in Github Desktop (or via command)

**Comment by tiamat71** [comment]
i never do that .... how can i do ?

when i try to create a pull request, the button is greyed

**Comment by istornz** [comment]
On github desktop, do you have checked all box ? 
![pull](https://cloud.githubusercontent.com/assets/16645312/17628890/bf44f920-60b7-11e6-9953-de965c46d251.jpg)

**Comment by tiamat71** [comment]
i have a message now : authentication failed, when i send a pull request

**Comment by istornz** [comment]
Try to disconnect and reconnect again

**Comment by istornz** [comment]
Now online thanks !
