### ISSUE TITLE
Consider using Flyover Maps

### ISSUE THREAD

**Issue by jwarhurst** [istornz/iPokeGo#223]
The MKMapTypeSatellite map type has basically been abandoned by Apple and has low quality and old imagery. In fact in iOS 9 Apple only uses MKMapTypeStandard /MKMapTypeSatelliteFlyover/MKMapTypeHybridFlyover in their Apple Maps app.

I'd suggest using these map types if user is iOS 9 or above.

**Comment by istornz** [comment]
Now added. I close.
Thanks for your suggestion !
