### ISSUE TITLE
Tapping the search icon does nothing

### ISSUE THREAD

**Issue by craziplaya21** [istornz/iPokeGo#226]
Is it just me or does the search icon not do anything right now? Everything else seems to work properly in the app. I can also search on my remote server through my home and mobile browser.

**Comment by istornz** [comment]
The search icon teleport you on the scanning pin annotation.
To place a scan annotation, do a long press on the map.

**Comment by craziplaya21** [comment]
Oh okay, that works differently than I was expecting! Is there no way to actually enter a location?

**Comment by istornz** [comment]
Actually no, but this feature is on the road map :)

**Comment by craziplaya21** [comment]
Okay, thank you. This app is so much better than the clunky web app interface. I will close this thread now.
