### ISSUE TITLE
Add toggle for "spawn points only"

### ISSUE THREAD

**Issue by MysticalOS** [istornz/iPokeGo#233]
Per https://github.com/PokemonGoMap/PokemonGo-Map/commit/d3eb8477d774886e76d05d955a6158058d10bd80

It's possible to map out an area first with a regular scan then enable spawn points only. The issue here is that of course you can't just run spawn points only all the time, so if you say for example move to a new location you need to flip it back to regular beehive to map the area first, THEN switch back to spawn points only. A toggle in app would help a lot.

**Comment by istornz** [comment]
Now added, I close.
