### ISSUE TITLE
Scan pin not showing.

### ISSUE THREAD

**Issue by SethG911** [istornz/iPokeGo#239]
Scan pin is not showing with the past few dev versions of PokemonGo-Map. Even though the pin is not showing, the scan location button is still showing. These are two separate issues that need to be addressed.

Also, just out of personal preference, I liked it better when the current location pin was blue, it makes it easier to see and it is also more in line with apple standards for current location indication. I would recommend changing it back from grey.

**Comment by dmunozfer** [comment]
When i add follow location feature (PR #214) i change user location pin to grey when follow location is disabled and blue when is enabled. Maybe we can change this behavior by another better.

**Comment by istornz** [comment]
@dmunozfer @SethG911 I added a notification when follow location is enabled/disabled. I think this is enough no ?

**Comment by SethG911** [comment]
@dmunozfer I did not realize the location indicator was behaving that way now. It makes sense, even though a bit unorthodox. Guess I just needed a reasoning rather than a fix. :)

Any thoughts on why the scan pin would not be showing though?

**Comment by dmunozfer** [comment]
@istornz I think that´s good

@SethG911 Scan button was hidden in commit [Hide radar button when scan pin is not set](https://github.com/istornz/iPokeGo/commit/2585b13aebee88270214c208eca8a4c00fd67e91). 
Could be that when application runs the last scan location point is not displayed?
If you marks new scan location point scan the button is displayed?
