### ISSUE TITLE
edit setting

### ISSUE THREAD

**Issue by tonygils** [istornz/iPokeGo#24]
hi,

how can i edit the ' hide very common' by myself?

**Comment by mattrat88** [comment]
Wondering the same

**Comment by philipp-r** [comment]
"hide very common" option is not implemented yet #3 
for configuration see #18

**Comment by istornz** [comment]
Now the functionality is working. Next func i want to add is custom pokemon hidden list.

**Comment by mattrat88** [comment]
Honestly props to you man , all I did to hide my unwanted Pokemon was locate the app via ifile and deleted the unwanted Pokemons sprites lol loving the tap and hold feature is there any chance we could get multiple area scans ? Or is that just too Farfetch'd lol
