### ISSUE TITLE
iPokeGo doesnt follow the Pokemon Go Map

### ISSUE THREAD

**Issue by denaelc** [istornz/iPokeGo#241]
iPokeGo only loads the pokemon at the location that i choose at my pokemon go map. I cant get it to load the pokemon at the location I choose in the app. If i click on the new york central Park (for example) on the map at the computer it loads every pokemon there and shows them in the app too. But if I choose a location at the iPokeGo app itself, lets say some other point in New York it doesnt show the pokemon there. I always need to change the location on the server first.
Any suggestions or similar problems?

**Comment by dmunozfer** [comment]
related? #231 

The app dont fetch scan location coordinates from map server

**Comment by blackhattristar** [comment]
I don't seem to be having any trouble changing my scan location from within the iPokeGo app.
