### ISSUE TITLE
Keeps loading and no pokemon...

### ISSUE THREAD

**Issue by Aakashmangla2000** [istornz/iPokeGo#243]
It just keeps loading and no pokemon is shown in the map. Why is this happening?

**Comment by istornz** [comment]
If you try to enter the url of the server on Safari, do you see any Pokemon ?

**Comment by mdk12** [comment]
I have the same problem since I updated today onto the newest release, my map works on all devices and browsers and used to work on 2.0.2

**Comment by istornz** [comment]
Please use the latest version v2.1 : https://github.com/istornz/iPokeGo/releases/tag/v2.1

**Comment by mdk12** [comment]
I already did and it doesn't work like I said in my previous comment
 "I have the same problem since I updated today onto the newest release"

**Comment by mdk12** [comment]
So after reinstalling 2.1 3 times it finally works
