### ISSUE TITLE
Crash with pokestops on

### ISSUE THREAD

**Issue by thisismohitgupta** [istornz/iPokeGo#245]
There are huge number of pokestops in the json response so we need to check if a pokestop or a gym is in for eg 10km....5km range of the scan location and add them to the map. If not done the app simply crashes due to memory issue

**Comment by dmunozfer** [comment]
Pokemon map raw_data endpoint has 4 parameters to set coordinates.. we could use this to reduce json results (and size):

[raw_data implementation](https://github.com/PokemonGoMap/PokemonGo-Map/blob/6d5e45be8a2d9873d58d6eb9351269945a552da9/pogom/app.py#L78)

**Comment by thisismohitgupta** [comment]
Already Implemented this @dmunozfer 
Thanks I will submit a pull request but there's a bug
When the user long clicks the second time on the map
The pokestops near old search location are removed and new ones are added near the new location. But the array which operates this is mutated simultaneously by two functions so I get an error - array mutated when iterating, any fixes for this ?

**Comment by thisismohitgupta** [comment]
Ok Fixed! The problem was lack of sleep apparently 😿
