### ISSUE TITLE
[help] how to make it work with pogom

### ISSUE THREAD

**Issue by hollingsbee** [istornz/iPokeGo#248]
hi there i use pogom and a iphone 6 can someone please help me on how to link the two?

**Comment by istornz** [comment]
Do you have setup any server ?

**Comment by hollingsbee** [comment]
Sorry is that a program? I was using nogrok (think thats how you spell it) but it doesnt seem that great so a app would be awesome

**Comment by Bizadon** [comment]
If you update an app you can see, that there is a choice to Pogom map or Pokemon Go map.

**Comment by hollingsbee** [comment]
I did download it yesterday has there been a update to the app to show that now has there?

**Comment by Bizadon** [comment]
I dont know, I've updated it several days ago and in settings I haver "Server type", don't you?

**Comment by hollingsbee** [comment]
Do i just have server address and thats all :/

**Comment by Bizadon** [comment]
It is very strange, I guess you are using api from here? https://github.com/istornz/iPokeGo/releases
If so - there is no changes with server, you need to download this https://github.com/istornz/iPokeGo/archive/master.zip and install it with xcode.

**Comment by hollingsbee** [comment]
isnt xcode for mac only?

**Comment by istornz** [comment]
@hollingsbee Yes

**Comment by istornz** [comment]
V2.2 IPA will be released in few days with full pogom supports

**Comment by hollingsbee** [comment]
@istornz ohh so i cant use this at the moment then as im on windows thats why i cant get it to work haha

**Comment by Bizadon** [comment]
@hollingsbee you can use VM for this

**Comment by hollingsbee** [comment]
what is VM?

**Comment by Bizadon** [comment]
virtual machine

**Comment by hollingsbee** [comment]
@istornz just curious do you have a eta on the release so i can use this on windows?

**Comment by istornz** [comment]
@hollingsbee I'm just finished the live visualisation of location. So i planned to release tomorrow I think 👍

**Comment by hollingsbee** [comment]
@istornz ahh amazing i will look forward to it then. thanks for you work

**Comment by istornz** [comment]
@hollingsbee V2.2 is now released 👍 https://github.com/istornz/iPokeGo/releases/tag/v2.2
