### ISSUE TITLE
App ID not available.

### ISSUE THREAD

**Issue by Azzivo** [istornz/iPokeGo#25]
<img width="453" alt="screen shot 2016-07-25 at 2 10 48 pm" src="https://cloud.githubusercontent.com/assets/20232511/17111921/b61f3dd2-5271-11e6-9540-5fdc5fc9c0dc.png">

Opened the project, plugged in my iPhone, signed in my team with my appleid.. and well I get this error.

**Comment by philipp-r** [comment]
Change the identifier in Xcode from 'com.dimitri-dessus.iPokeGo' to something like 'com.YOUR_NAME.iPokeGo'. 
Should work then

**Comment by Azzivo** [comment]
Thank you it worked, but now I'm getting an error stating I need Xcode 8. Completely forgot 7.3.1 won't work. I'll try it once I do that.
