### ISSUE TITLE
follow location bug

### ISSUE THREAD

**Issue by Jones1337** [istornz/iPokeGo#252]
i think the app can't handle the follow position feature while running in background.

**Comment by dmunozfer** [comment]
We have 2 CLLocationManager, one in AppDelegate and the other in MapViewController. 

Perhaps we should make the delegate of CLLocationManager in AppDelegate was MapViewController? Is it possible?

**Comment by Jones1337** [comment]
+ I think it's not good to deactivate follow position when you zoom out to see more pokemon. Everytime I zoom out, I have to press and hold the position button again to reactivate scan follow position feature

**Comment by dmunozfer** [comment]
Follow location only should be disabled when user scrolls map with 1 finger.. zoom should not disable it. Are you using the latest version?

**Comment by Jones1337** [comment]
yes, i am. and i just found out, when you scroll the map it's deactivated again :/

**Comment by dmunozfer** [comment]
Using ios 9.3 and iPhone 6 do not have that problem. What versions do you use?

**Comment by SnakeIz** [comment]
Why am I not seeing a follow location option? I have it connecting to pokemongo-map?

**Comment by Jones1337** [comment]
@dmunozfer exactly the same, iOS 9.3 + iPhone 6 ...

**Comment by dmunozfer** [comment]
@SnakeIz to enable follow location do long press on gps button
@Jones1337 I can not have the same behavior... can you try to pan/scroll with 2 fingers? what it does?

**Comment by Jones1337** [comment]
With two Fingers it doesnt happen but i think it shouldnt fail with one finger?!

**Comment by dmunozfer** [comment]
This feature was implemented in this PR #214 
@istornz @markvl91 Maybe we should enable/disable this from settings?

**Comment by istornz** [comment]
@dmunozfer Yes, I think it's more intuitive :)
