### ISSUE TITLE
Add more accounts

### ISSUE THREAD

**Issue by denaelc** [istornz/iPokeGo#253]
Is anyone able to get more than one account to run? I personally cant seem to be able to use more than one without getting an error of some kind. Here is the command i tried:

python ./runserver.py -a ptc -u username -p password -a ptc -u username2 -p password2 \
 -l location -st 3 -k “google maps key“

if any1 knows how to get it working for 2 or more accounts, tell me :)

**Comment by istornz** [comment]
I use pogom to run multiple account, it's more easy because you can add some of them in settings page on the website (xx.xx.xx/config)

**Comment by mlc130104** [comment]
If you use Pokemongo-map, use ./config/config.ini for better multiple account support.
