### ISSUE TITLE
iPokeGo issue

### ISSUE THREAD

**Issue by Made123** [istornz/iPokeGo#257]
Hellow all,

I have only one server with many account. i can launch one process with multiple (large zone but slow scanning area) and/or another process with one account with a small area (faster scan).

If i launch the two process by writing on the same db, i often have the message "error database is locked". Then i can let you guess what happen with many process with 1 account..

I know that iPokego can not read from two different locations db, then my question is: "Is it possible to install 2 version of iPokeGo ?"
Like iPokeGo1 and iPokeGo2. Like this i can read from two different location and have the nofications in background.

**Comment by istornz** [comment]
iPokeGO does not read the db file but a JSON file. So please ask your question to Pokemon-GO Map 👍
