### ISSUE TITLE
Server switcher?

### ISSUE THREAD

**Issue by mlc130104** [istornz/iPokeGo#259]
I currently run one Pokemongo-map and one pogom instance for near-home spawn point scanning and downtown hunting respectively. Is it ever possible to add a server config tab for fast server switching?

**Comment by istornz** [comment]
Yeah, it's on the road map. First, I want to finalize the full supports of Pogom server.

**Comment by mlc130104** [comment]
Oh well, that just remind me I was redirected here from a Reddit post advertising your app supports pogom, yet I changed my regular scanner to Pokemongo-map as pogom is exhausting my accounts  before you finally published an updated IPA few hrs ago lol

Anyway your app is awesome, saved me much time on hunting pokes, and I do have few more suggestions to improve it. Should I list them here in this issue thread or I need to open a new one? Please advise.

**Comment by istornz** [comment]
@mlc130104 Thanks, please open issues for enhancement 👍

**Comment by istornz** [comment]
Now added.

**Comment by Bizadon** [comment]
@istornz can you add opportunity to edit server?
