### ISSUE TITLE
Installed App fine onto iOS but no pokemons show up on the map.

### ISSUE THREAD

**Issue by ahcloud88** [istornz/iPokeGo#26]
Am i doing something wrong here? Don't see any other steps i was suppose to do. I tried changing server to localhost:5000. Do i need to be running another program on the cpu while having this app open?

**Comment by ahcloud88** [comment]
i have the python running in the background and used a shared link forward as the server but no pokemon still shows up on my phone app

**Comment by istornz** [comment]
You have to put the network address of your computer. Localhost is the local address of your machine. To search the IP address : http://www.howtogeek.com/236838/how-to-find-any-devices-ip-address-mac-address-and-other-network-connection-details/

**Comment by harrybui2592** [comment]
I could not see any pokemon shown either.
I'm using app with 4G mobile data on Iphone. What server I have to change to?

**Comment by rizardhis** [comment]
i found a same problem, if my IP is 192.162.100.2, then shoud i put http://192.168.100.2:5000 to the serverbox? please respond tks

**Comment by jankcat** [comment]
You need to use your public IP, and set up port forwarding on your router.
https://whatismyipaddress.com/
http://www.pcworld.com/article/244314/how_to_forward_ports_on_your_router.html

**Comment by harrybui2592** [comment]
Can someone give me an example please?

**Comment by istornz** [comment]
@rizardhis With the new version of the project, yeah put "http://192.168.100.2:5000"

**Comment by dreyershelby** [comment]
hi, i did what @istornz said to do and its still not working. im working with a remote server since the other website couldn't get my ip for some reason
