### ISSUE TITLE
Desyncing

### ISSUE THREAD

**Issue by MysticalOS** [istornz/iPokeGo#266]
Didn't really have this problem before. It just started up. The app will often desync and stop refreshing pokemon, like it's lagging behind the webhook and force restarting app is only way to clean it up. usually when this happens i can tell because notifications stop coming for stuff I know that spawned (and i'll double check and they show on web driver but not app). Furthermore when this happens I often see blinking pokemon in the app. I'm wondering with all the recent changes to the webhooks and making it's own thread/etc if it's bugging out on app end or server end.

**Comment by istornz** [comment]
Yes, I have this problem too, I will fix it asap (a workaround is to open settings and directly close to force refresh).

**Comment by MysticalOS** [comment]
Actually that doesn't always work, sometimes but not always. Sometimes the flashing pokemon don't go away. That might be a separate issue, when they start flashing glitching. also when that happens if any of flashing ones are notify mobs, it triggers a new notification every flash.

**Comment by foltincsaba** [comment]
I have similar problem, but my temporary fix is different.
The app doesn't refresh the pokemons. I cannot force refresh by force closing. It doesn't do anything. The only way I can have the app to refresh the pokemons is by pressing the home button twice, switch to another application, and than switch back iPokeGo with pressing home button twice again.

**Comment by foltincsaba** [comment]
It seems to work now. I started using localtunnel https://github.com/localtunnel/localtunnel instead of ngrok, and now it's ok.

**Comment by istornz** [comment]
Now fixed.
I close
