### ISSUE TITLE
Favorite notifications have stopped working 

### ISSUE THREAD

**Issue by racerx8967** [istornz/iPokeGo#269]
Favorite Pokemon notifications have stopped working since last update. Even when downgrading not working.. Please fix asap iOS 9.3.3 Pokemon go++ 1.5r15

**Comment by istornz** [comment]
Please test the latest master version (not ipa)

**Comment by racerx8967** [comment]
I'm not using ipa and according to repo I'm up to date... Is there a repo that's not beta? Am I missing something?

**Comment by istornz** [comment]
@racerx8967 Nope, master is the beta build and IPA are "stable" release :p

**Comment by racerx8967** [comment]
Ok as stated above I'm using the current and have downgraded previous versions and still nothing has worked. Also it has happened on 2 of my buddies devices as well. Seems like when something else was updated (one of the components) is what broke it. Anyone else having this issue? It makes it extremely hard to find the right Pokemon if you're in a large area with over 200 Pokemon spawning at once. Any support from someone who knows... Would be great. Thank you.

**Comment by istornz** [comment]
@racerx8967 I just tested on my iPhone and fav notification working great. What is the type on notification which not work on your device (real notification, in-app notification or both) ?

**Comment by racerx8967** [comment]
All 3 devices running iOS 9.3.3 jailbroken with paingu running latest build from Cydia unlimited apps beta repo. All are iPhone 6s+. The favorite notification is not working inside the app or with outside notifications. I've tried reinstalling the game the hack and everything else.. We are out of ideas. No red bar and no notifications say when browsing safari. Very frustrating.

**Comment by racerx8967** [comment]
Something also strange is the app badge is stuck at 7 notifications for all of us.. No way to clear them.

**Comment by racerx8967** [comment]
Also does not show time the Pokemon will disappear it only has a picture of a steering wheel...

**Comment by racerx8967** [comment]
Does Pokemon go rely on adtools?

**Comment by racerx8967** [comment]
Ignore last comment

**Comment by istornz** [comment]
Very strange I have an iP6+ Jailbroken on 9.3.3 too but it works...
Do you have selected favorite Pokemon in the list, if yes test to show only favorite Pokemon on the map and tell me if it's working.

**Comment by istornz** [comment]
Normal notifications works ?

**Comment by racerx8967** [comment]
No we are all reporting no notifications at all working. Time till disappear just shows a steering wheel. Hide commons works, show only favorites works. But no notifications are working at all. We have triple checked everything. Notifications are on, favorites are selected, notify of favorites is on... Have downgraded to every version to check still not working. Uninstalled all other tweaks in Cydia.. It's like notifications are stuck somewhere and this defiantly happened during a revision change.. I'm not sure which one though that's the problem. Before that they were working fine.

**Comment by racerx8967** [comment]
No we are all reporting no notifications at all working. Time till disappear just shows a steering wheel. Hide commons works, show only favorites works. But no notifications are working at all. We have triple checked everything. Notifications are on, favorites are selected, notify of favorites is on... Have downgraded to every version to check still not working. Uninstalled all other tweaks in Cydia.. It's like notifications are stuck somewhere and this defiantly happened during a revision change.. I'm not sure which one though that's the problem. Before that they were working fine. 

Sent from my iPhone

On Aug 24, 2016, at 6:26 AM, Dimitri Dessus <notifications@github.com> wrote:

Normal notifications works ?

**Comment by racerx8967** [comment]
Fixed in today's update!! Thank. You!
