### ISSUE TITLE
Pogom timer bug

### ISSUE THREAD

**Issue by Bizadon** [istornz/iPokeGo#274]
Sometimes when I use pogom server a bug appears in app. But in browser version everything allright with time. Seems like there is two timers over a pokemon laid one over another.

![image](https://cloud.githubusercontent.com/assets/20676961/17885440/ffce0498-6925-11e6-9c1a-e3f90202ceff.png)

**Comment by Bizadon** [comment]
@istornz What is with it?

**Comment by istornz** [comment]
@Bizadon If you open settings and directly close the tab do you have the same bug ?

**Comment by Bizadon** [comment]
@istornz yes, the same, but I dont know is it important now, because it seems that pogom doesnt work on their map...

**Comment by istornz** [comment]
@Bizadon @TheNewDarkOne I think the problem is fixed with the latest commit, can you confirm plz ?

**Comment by istornz** [comment]
I close this issue please reopen if needed.
