### ISSUE TITLE
Pokemon not showing up at all 

### ISSUE THREAD

**Issue by Stephieelee** [istornz/iPokeGo#275]
As above

**Comment by istornz** [comment]
Do you see any pokemon when you type the same url on safari ?

**Comment by SethG911** [comment]
I am having the same issue upon first opening the app. If I press home, then come back to the app, or close the app and start it again, it seems to fix the issue until the next time I start the app.

**Comment by toshioson** [comment]
Sorry but I am having the same issue using iPokeGo on my iPad mini.

It works with the same URL on safari on the iPad mini and when I startup that on safari (or on my desktop), iPokeGo will starts to show pokemon but it just will not start scanning with iPokeGo alone.

How to trigger the scanning? Is there a button or swtich in iPokeGo to do so? Sorry but I cannot find one. 

Thank you in advance for looking into this.

**Comment by leolobato** [comment]
Same issue here. I can see the app actually hitting the server URL but will not display results most of the time.

After a while waiting, I'll see a timeout error on the console (probably from an old request?) and *some* pokemons will show on the map, but not all of them (validating against the actual server URL on desktop browser).

**Comment by istornz** [comment]
Fixed.
I close.
