### ISSUE TITLE
ipokego, am i doing wrong? 

### ISSUE THREAD

**Issue by Dcaneman** [istornz/iPokeGo#276]
I just tried to install the app for hours and finally did it and it didnt show any pokemons at all. It said something about server, and i read the wiki which said you could put your ip or something and i tried all of it and localhost 5000. 

I am not really into stuff like servers, so im kinda noob. 

Does it work work someone? If it does, could you please try to help.

Or maybe i just did wrong? i think i did good until i started the app on my iphone. What are you suppost to do after that? i cant find anything on either youtube or google. 

So i would really really appreciate some help.

**Comment by istornz** [comment]
You have to find your computer's local IP address or remote IP address if you want to use outside.
http://www.howtogeek.com/117371/how-to-find-your-computers-private-public-ip-addresses/
When you have your IP address just type : 'http://xx.xx.xx.xx:5000' (xx.xx.xx.xx is you IP address).
Be careful to choose the right type of your server (Pogom or PokemonGo-Map).

**Comment by Dcaneman** [comment]
okay i tried putting it in but it doesnt really happen anything?  am i suppost to do anything with a pc to get this to work? 

Would be very nice if there was a tutorial how to set it up. 

does it even work? 
Do you know any other scanners, that works atm?

**Comment by robiningelbrecht** [comment]
You can use ngrok (http://ngrok.io) to expose your local machine to the internet. ngrok will then generate an URL for you (for example: https://123abc.ngrok.io). You can use that URL to configure your iPokeGo app

**Comment by istornz** [comment]
@Dcaneman Check this tutorial : https://pgm.readthedocs.io/en/develop/basic-install/index.html

**Comment by Dcaneman** [comment]
im getting so angry, after hours of trying it still fucks up. i dont find any "pip" or anything. Why is all this so advanced, and the tutorial is so shitty...

**Comment by Dcaneman** [comment]
any youtube videos that shows? And BTW, does it even work for any of you? if it does, tell me.

**Comment by Dcaneman** [comment]
My problem is at this: 

Installing Modules
At this point you should have the following:

Python 2.7
pip
PokemonGo-Map application folder
First, open up your shell (cmd.exe/terminal.app) and change to the directory of PokemonGo-Map.

You can verify your installation like this:

python --version
pip --version
The output should look something like:

what should i do?

i just installed the release verision, but dont see any files in it to install. Its just a a bunch of files that i cant do something with. And i dont understand what files it means with python 2.7, pip and pokemongo-map.  

Help please

**Comment by istornz** [comment]
@Dcaneman Check this video tutorial it's very well explained : https://www.youtube.com/watch?v=RJKAulPCkRI

**Comment by Dcaneman** [comment]
@istornz But the thing is its not the same files, he is using a older version and the steps he do i cant do because i dont have the same files. What should i do?`any new video?

**Comment by Dcaneman** [comment]
@istornz  Hey its now working :))
both the ipokego and the pokemongomap, but will ipokego work if i go out? 
And how do i get to scan more places? 
My city is not to big so i wanna scan the most of it. How do i get more hexagons? do i need more accounts? and how do i add that in the cmd?

**Comment by robiningelbrecht** [comment]
Have you even did an effort to read the documentation? All your questions are answered there. This is not a support forum....
https://pgm.readthedocs.io/en/develop/

**Comment by istornz** [comment]
@Dcaneman Nice :)
Yes check the doc for this question. I close
