### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by tsuncp** [istornz/iPokeGo#278]
NSArray *gymsToRemove = [annotations filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"self isKindOfClass: %@ AND self.gymID IN %@" argumentArray:@[[GymAnnotation class], self.annotationsGymsToDelete]]];

2016-08-24 19:22:08.913 iPokeGo[5265:1203622] Fetched data
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by SethG911** [comment]
I'd assume that this commit (1dde507) has something to do with this? Could this possibly solve the issue, or is it the cause? Are you running the latest version?

**Comment by tsuncp** [comment]
yes.
i tried to solve the problem by using the latest version. however , it didn't fixed
i need to reinstall the app to solve the problem.

**Comment by tsuncp** [comment]
because this issue happened before and after the latest version. Maybe it isn't belong to the commit?

**Comment by istornz** [comment]
@tsuncp This bug was already present before the commit

**Comment by tsuncp** [comment]
2016-08-26 20:25:03.093315 iPokeGo[281:10656] -[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x17066f440
2016-08-26 20:25:03.097669 iPokeGo[281:10656] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x17066f440'
*** First throw call stack:
(0x18ac681c0 0x1896a055c 0x18ac6f278 0x18ac6c278 0x18ab6659c 0x100108990 0x100105050 0x18b265618 0x18b27c318 0x18b7287e4 0x18b66d358 0x18b65d954 0x18b72ab90 0x10023521c 0x100242b54 0x100238ce4 0x100244e6c 0x100244bb8 0x189cf92c8 0x189cf8db4)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

if enabled showing gym in the latest version

app will crash.

**Comment by beastliest** [comment]
I'm having this issue with the latest version too.
