### ISSUE TITLE
Add to appstore

### ISSUE THREAD

**Issue by zubr93** [istornz/iPokeGo#28]
Someone can add this to app store? - No MAC OS currently and AMD PC ;__;

**Comment by jankcat** [comment]
I have submitted it to Beta Review, which should at least let us know what issues will arise/need to be fixed before it can be submitted to the AppStore... @istornz if it passes, I have no problem submitting it and including your copyright notice with it. I already pay the yearly fee for other projects anyways.

**Comment by istornz** [comment]
I have a paid account too. When the porting will be more advanced I will put the app online on the App Store.

**Comment by HypeZ85** [comment]
any news about this? i just setup my own server and it will be very handy to download iPokeGo from appstore <3
