### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by kevdotcom** [istornz/iPokeGo#280]
As there is no private messaging feature on Github and I don't know how to contact you personally, I hope it's okay, that I post my question here.

We are currently hosting a PokemonGo-Map for our city and would like to provide a version of iPokeGo with our server hardcoded inside it... Can we just download the code and do that? We would link to your website and write something like "Powered by iPokeGo, written by istornz". We wouldn't even change the logo, just hardcode the server for easier use :)

I know it's all in the license, but I still wanted to ask before just ripping your app basically.

**Comment by istornz** [comment]
Hello, yes no problem the MIT license allows you to do anything with this project. You just have to include this license file on your project : https://github.com/istornz/iPokeGo/blob/master/LICENSE
