### ISSUE TITLE
Error processing server's data

### ISSUE THREAD

**Issue by AmauryVela** [istornz/iPokeGo#281]
I´m getting this issue with pokemap version 3.1.0

Error processing server's data: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

Does anyone know why?

**Comment by istornz** [comment]
Have you still got the same problem?

**Comment by AmauryVela** [comment]
No, I think was PokemonGoMap issue, the server response html code before the json data. On the latest release works like a charm
