### ISSUE TITLE
Upated version not working

### ISSUE THREAD

**Issue by lexthefalex** [istornz/iPokeGo#288]
My app got updated automatically to version 2.0 and it does not work (shows no pokemon) despite uninstalling and installing several times. Is there a way to download version 1.0 again?

**Comment by istornz** [comment]
Automatically ?? It's not possible^^
On the server field do you have set the "http://" before the IP addr ?

**Comment by lexthefalex** [comment]
Or rather its lagging badly and cannot show all pokemon as compared to the
previous version especially when i show favourites and hide common.

Any solutions to this? I am using my ipad for this

**Comment by istornz** [comment]
Do you have Pokestops/gyms enabled ?

**Comment by lexthefalex** [comment]
Hi Dimitri,

Nope, and I have lesser pokemon selected for favourites compared to my
friend. have tried reinstalling several times..
Any possible solutions?

Thanks!

**Comment by istornz** [comment]
What is the exact version (it's on the Settings tab at bottom) ?

**Comment by lexthefalex** [comment]
Hi i cant view it. See attached

On Monday, 29 August 2016, Dimitri Dessus <notifications@github.com> wrote:

>

> What is the exact version (it's on the Settings tab at bottom) ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/istornz/iPokeGo/issues/288#issuecomment-243053346>, or
mute the thread

**Comment by istornz** [comment]
Oh do you use GO Radar ??

**Comment by lexthefalex** [comment]
Yes i am using that

**Comment by istornz** [comment]
@szlyrhjm GO Radar is not my app.
This app use a modified version so please contact : https://twitter.com/miniroo321
