### ISSUE TITLE
GoRadar version 2.0 not workkng

### ISSUE THREAD

**Issue by Patatou** [istornz/iPokeGo#289]
Hi,

Since yesterday update for GoRadar v2.0 on my iPhone via the Apple Store, the App is totally buggy, doesn't show pokemon.

For comparaison, i take 2 iPhone One with v1 and 2nd with v2, and v1 working good when v2 bug...

Any patch soon ?

Ty

**Comment by Patatou** [comment]
Precision : v2 working a little big on iPhone and not at all on iPad.

**Comment by Patatou** [comment]
And multilanguage version doesn't work anymore in v2.
(In v1 everything is un French , my phone language... In v2 everything is in english)

**Comment by istornz** [comment]
GO Radar is not my app. 
Please contact : https://twitter.com/miniroo321
