### ISSUE TITLE
Pokestops and Gyms not showing

### ISSUE THREAD

**Issue by szlyrhjm** [istornz/iPokeGo#290]
Pokestops and Gyms are not showing up on my app (iPhone 6 with latest iOS). Pokemon work fine though. Any ideas? Thx

**Comment by istornz** [comment]
What is the type of your server ? (Pogom or Pokemon-GO Map)

**Comment by szlyrhjm** [comment]
On my iPhone over LTE cell connection. How can I find what type of server?

**Comment by szlyrhjm** [comment]
It's the "Go Radar" app on my iPhone.

**Comment by istornz** [comment]
@szlyrhjm GO Radar is not my app. 
Please contact : https://twitter.com/miniroo321
