### ISSUE TITLE
[help] build iPokeGo in xcode 8

### ISSUE THREAD

**Issue by Jones1337** [istornz/iPokeGo#291]
hey guys, since last commit (5 hours ago) i can't build and install the latest commits.
error code: 

 
    duplicate symbol _ShowFetchedDataStatusNavBar in: 

    /Users/jones/Library/Developer/Xcode/DerivedData/iPokeGo-aayfjbmjjsizbterdbiztpefjmmr/Build/Intermediates/iPokeGo.build/Debug-iphoneos/iPokeGo.build/Objects-normal/arm64/MapViewController.o

    /Users/jones/Library/Developer/Xcode/DerivedData/iPokeGo-aayfjbmjjsizbterdbiztpefjmmr/Build/Intermediates/iPokeGo.build/Debug-iphoneos/iPokeGo.build/Objects-normal/arm64/AppDelegate.o

    duplicate symbol _ShowFetchedDataStatusNavBar in: 

    /Users/jones/Library/Developer/Xcode/DerivedData/iPokeGo-aayfjbmjjsizbterdbiztpefjmmr/Build/Intermediates/iPokeGo.build/Debug-iphoneos/iPokeGo.build/Objects-normal/arm64/MapViewController.o 

    /Users/jones/Library/Developer/Xcode/DerivedData/iPokeGo-aayfjbmjjsizbterdbiztpefjmmr/Build/Intermediates/iPokeGo.build/Debug-iphoneos/iPokeGo.build/Objects-normal/arm64/iPokeServerSync.o 

    ld: 2 duplicate symbols for architecture arm64 

    clang: error: linker command failed with exit code 1 (use -v to see invocation)`

For me it seems that a variable or function called "ShowFetchedDataStatusNavBar" is set multiple times but i didnt find any multiple annotation :/

i already cleaned the project and deleted derivedData... i did download the latest zip again and tried it several times... really don't know how to solve this problem.

please help :)

**Comment by istornz** [comment]
Thanks, now patched
