### ISSUE TITLE
[feature] Save Server

### ISSUE THREAD

**Issue by Jones1337** [istornz/iPokeGo#292]
Hi @ devs.

What about adding a feature, where you can saving a string containing "ip:port", which can be selected in a dropdown-menu in settings --> Server.

I like the idea of saving multiple servers just for reasons of time, e.g. if I just want to switch to localhost at home or if i use other scanners.

What do you think?

**Comment by istornz** [comment]
It's a good idea, this feature was already submitted on #259

**Comment by istornz** [comment]
Now added.
