### ISSUE TITLE
Updated to new version, cant see any pokemon

### ISSUE THREAD

**Issue by lemupuffy** [istornz/iPokeGo#293]
Updated to the new version and cant see any pokemon.

**Comment by istornz** [comment]
What is your version ?

**Comment by lemupuffy** [comment]
Go app 2.0, iphone 5 ios 9.0.2

**Comment by lemupuffy** [comment]
Go radar app is 2.0 iphone 5 running ios 9.0.2

**Comment by istornz** [comment]
@szlyrhjm GO Radar is not my app. 
Please contact : https://twitter.com/miniroo321
