### ISSUE TITLE
App Crashes on Gym Switch activation

### ISSUE THREAD

**Issue by beastliest** [istornz/iPokeGo#298]
Just cloned the latest copy (2.3) and whenever the Show Gym toggle is activated, the app crashes. Happens on my older 2.2 copy either.

2016-08-29 18:09:55.120 iPokeGo[4801:752689] -[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1491f47c0
2016-08-29 18:09:55.121 iPokeGo[4801:752689] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1491f47c0'
*** First throw call stack:
(0x180e16db0 0x18047bf80 0x180e1dc4c 0x180e1abec 0x180d18c5c 0x1000ab704 0x1000a7d94 0x181403400 0x181415f80 0x1817d0540 0x181722870 0x181712e48 0x1817d2934 0x1001c1a3c 0x1001ce554 0x1001c572c 0x1001d066c 0x1001d0364 0x180a79470 0x180a79020)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by istornz** [comment]
What is the type of server do you use ? (PokemonGO-Map or Pogom ?)

**Comment by beastliest** [comment]
PokemonGo-Map

**Comment by istornz** [comment]
Try to shutdown the server and delete the pogom.db file and start again.

**Comment by TRingo1** [comment]
I just did a clean install new pogom.db file created on map server, and the app crashes each time i enable the gym. 

IPhone6 - 9.3.5 iOS
Ipokego - latest copy from master
pokemongo-map - server just updated to latest versions using --update method

**Comment by beastliest** [comment]
Yeah, same at @TRingo1

**Comment by istornz** [comment]
#301

**Comment by istornz** [comment]
I close this issue please use the other one :)

**Comment by istornz** [comment]
Now fixed.
