### ISSUE TITLE
pokemon showing up are a bit wonky

### ISSUE THREAD

**Issue by SkOODaT** [istornz/iPokeGo#3]
Even with hide common types off some pokemons are still not appearing even though they are on my browser window

**Comment by fraannk** [comment]
Same. No Pidgeys, Rattatas and so on, on my map. They are shown on the server though.

**Comment by istornz** [comment]
Yeah it's normal, this function is not implemented yet on the code but option are visible on settings.
I will add this functionality asap.

**Comment by mydonny1986** [comment]
You can just replace the pokemon photo with a blank one then they won't show up in the map, just a work around
