### ISSUE TITLE
null Error

### ISSUE THREAD

**Issue by ZihanTang** [istornz/iPokeGo#30]
Hi there,
After installing the app, it does not work for me. I checked the log, there is a null Error. Did you know the reason, here is the log.
![screen shot 2016-07-25 at 10 49 46 pm](https://cloud.githubusercontent.com/assets/12687471/17124614/697e091a-52ba-11e6-9a31-6b4f6fa8cb2e.png)

**Comment by istornz** [comment]
Hello, do you have the very latest version of the project ?

**Comment by ZihanTang** [comment]
Thanks. It seems like that I installed a previous bug version, latest version do not have this problem.
closed.
