### ISSUE TITLE
Do I need to forward my port?

### ISSUE THREAD

**Issue by kschultee** [istornz/iPokeGo#300]
Installed the app and also have a Pokemon Go Map server running. Attempting to connect it via Settings>Server (local ip:5000) however nothing appears on the map on my phone, however on my comp. it does. So this leads me to believe I may need to port forward. Thanks.

**Comment by istornz** [comment]
Hello, please enter the ip addr on Safari and tell me if you see any Pokemons.

**Comment by kschultee** [comment]
Wasnt sure whether you meant on comp or iPhone so did on both

iPhone: Nothing... Says cannot connect to the server

Comp: localhost:5000 works great... can see pokemon. Just cant on iphone

**Comment by cyan** [comment]
you have to put the server address, if you use it from outside your network (like on the road with 4g, yes you have to foward your port for the server)

**Comment by istornz** [comment]
I close the issue, please open a new one if the problem persist.
