### ISSUE TITLE
App crash with desktop map 0.3.3

### ISSUE THREAD

**Issue by iCiccio25** [istornz/iPokeGo#301]
When I save the server's link in the app it crash

**Comment by caustinbrooks** [comment]
I'm having the same issue. It occurs upon toggling the gym info switch. I have the advanced gym info running on my webserver, I would imagine that there is a conflict with the how the data is transmitted now.

**Comment by istornz** [comment]
Now fixed.
I close

**Comment by iCiccio25** [comment]
I redownload ipa but it's continue to crash :/

**Comment by beastliest** [comment]
Make sure you're running version 2.3 (not in the releases. compile it in Xcode)
