### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by skosi123** [istornz/iPokeGo#305]
Hi, can I ask you, when you plan to make new ipa file? In last days here was much changes, but last release is 16 days old. I'm windows user and i think that ipa file is the only way, how to get new update. I'm so sorry for my bad english.

**Comment by istornz** [comment]
The new version is coming soon.
I'm currently working ln the last feature (Server switcher). Once this feature is finished, i will release the new version.

**Comment by skosi123** [comment]
OK, thank you, that is great :+1:

**Comment by Dcaneman** [comment]
the current version is pretty shitty, atleast on my iphone SE, you cant see the time until it despawns on most of the pokemons, only the 2 first numbers (hour) is viewable. Which doesnt help anything.  You can only see the timer on the pokemons that is "rare" or "common". the longer names such as "very rare", "ultra rare" and "uncommon" you cant see the timer on. 

And the app is not updating, you have to close it and wait for about 5 min and then go back into the app and wait and then it will load the pokemons.

The webbrowser version is so much better, and i am using it right now.

**Comment by skosi123** [comment]
Dcaneman: I have iphone SE too and if you mean the version v2.2, than i must say, that it works much better for me, than webbrowser (because in webbrowser it is too slow). Problem with the timer you can solve in settings->Pokemons->Show Time.  And I'm online wint my server all the time, i dont need any restart of this app, it run on background 24/7 and if is something interesting on map, than i get notification. I have only one problem - gyms, i must turn it off.

**Comment by jessiewestlake** [comment]
I'm using v2.2 on iPhone 6+ and the app is amazing. Way better than the web browser. I love the push notifications. I just can't figure out how to have scan follow my location.

**Comment by Dcaneman** [comment]
maybe you guys like it, but for me i have a tons of problems however it works. 
I dont see the negative thing with the browser, its very good. more futures.

**Comment by istornz** [comment]
Server switcher functionality is now online.
If anyone can test it would be very nice :)

**Comment by skosi123** [comment]
I would like to test it, but I don't know how can I get IPA file for cyda.

**Comment by TRingo1** [comment]
@istornz just loaded the latest release with server switcher, it carried over a lot of my setting once i added the server profile. ill post any issues.  i don't run pogom server, will try to set one up to test the switching mode. nice job!  once i enter the server profile config, i need an Edit mode to change my port settings, not sure how to do this yet.

**Comment by TRingo1** [comment]
@istornz also need to add ability to delete a server profile.

**Comment by istornz** [comment]
@TRingo1 Just swipe on cell

**Comment by TRingo1** [comment]
Delete cell worked fine by swiping to the left.

**Comment by istornz** [comment]
Please open issues if you have any enhancement or bug with this new feature.

**Comment by TRingo1** [comment]
@istornz i had loaded the POGOM server, and not sure i know how that server work completely, but could not get any pokemon to appear on the ipokego app.

**Comment by istornz** [comment]
@TRingo1 Try the latest build.
Do you see any pokemon on the website ?

**Comment by ro4sho** [comment]
Is there a new release? I still see the old one.

**Comment by istornz** [comment]
V2.3 is now out 👍 
I close this issue.
