### ISSUE TITLE
go radar is unstable ....

### ISSUE THREAD

**Issue by pokemaster93** [istornz/iPokeGo#306]
radar official .... your apps is unstable , sometimes show the Pokemon but sown times won't show at all.... need to relog lot of time or delete the apps and download again ....... and the ONlY SHoW FAVourite....when on.... it's didn't show Pokemon....please fix that ... thanks .... and hope u increase the snorlax and dragonite spawn rate ......

**Comment by istornz** [comment]
GO Radar is not my app. 
Please contact : https://twitter.com/miniroo321
