### ISSUE TITLE
fix GO RADAR / Malaysia country 

### ISSUE THREAD

**Issue by pokemaster93** [istornz/iPokeGo#307]
hello , go radar official ... please fix the spawn rate about Snorlax and dragonite , it's only shown 1 each time only ...... and the Radar apps is unstable , sometimes won't show the Pokemon icons there ...... please fix it and fix the SHOW ONLY FAVOURITE " when I ON it, it's didn't show my FAVourite Pokemon ......  please fix the appear rate ....in Malaysia .....KYa later lumpur 
![image](https://cloud.githubusercontent.com/assets/22016794/18259674/294d172a-7419-11e6-9659-53b63f4d226b.jpeg)

**Comment by istornz** [comment]
GO Radar is not my app. 
Please contact : https://twitter.com/miniroo321
