### ISSUE TITLE
How can I configure server?

### ISSUE THREAD

**Issue by were** [istornz/iPokeGo#308]
I have installed this software, but I cannot use this software to view PokeMons.

I am suffering from the problem I cannot find a proper server to connect to.

Any recommendation?

**Comment by istornz** [comment]
First you have to setup our server : https://pgm.readthedocs.io/en/develop/basic-install/index.html
When your server is operational, just add the ip address on the app.

**Comment by were** [comment]
Is there any existing server recommended?
I have a friend who installed Android version, and he had no need to set up server.

**Comment by istornz** [comment]
I prefer Pogom server.
