### ISSUE TITLE
Pokestops not showing up

### ISSUE THREAD

**Issue by nardavin** [istornz/iPokeGo#31]
Regardless of the show pokestops setting, pokestops are not rendering on the map. Pokestops appear normally on the webapp.

**Comment by jankcat** [comment]
Seconded. Also not seeing stops, or some gyms

**Comment by Sweetfire37** [comment]
Same for me, no pokestops.

**Comment by fraannk** [comment]
Changing the pokestop part in the code to "true" fixes it. But only until you change location, then you'll need to turn the setting on and off again. :)

**Comment by istornz** [comment]
Now fixed thx for report
