### ISSUE TITLE
Go Radar Singapore not showing any pokemons 

### ISSUE THREAD

**Issue by vanessading** [istornz/iPokeGo#310]
Dear Go Radar administrator,

The Go Radar app is not working. It does not show any pokemon icon when the setting is on. It does not help either when I reload the app or reboot my mobile. I am having great difficulties searching for my favourite Pokemon. Will really appreciate if you can fix Go Radar in Singapore at your soonest possible. Thank you very much for your kind assistance. Have attached the faulty Go Radar map below.

![image](https://cloud.githubusercontent.com/assets/22063003/18332394/c68f58ce-7598-11e6-9b24-344d638ef141.png)
![image](https://cloud.githubusercontent.com/assets/22063003/18332395/c6fb5fce-7598-11e6-9a9b-4f88ae8b754d.png)

**Comment by pandapo411** [comment]
Where you get this version? Go Radar of mine have different GUI.

**Comment by istornz** [comment]
GO Radar is not my app. 
Please contact : https://twitter.com/miniroo321

**Comment by vanessading** [comment]
One of the u-tuber recommended downloading Cydia Impactor together with PokemonGo150Hack.ipa.
