### ISSUE TITLE
Server List pre-filled

### ISSUE THREAD

**Issue by bouelcom** [istornz/iPokeGo#316]
Is there any whay to create a list of servers that still in the app natively ... instead of entering them manually each time i reinstall the app ? If yes, How-to ?

Exemple, i currently have 5 Pokemongo-map server running 24/7, i would like to include them in the app , so when my friend install the app, they already have them in the list of server !

**Comment by vraposo** [comment]
You can change the source code, build a version and give it out to your friend.
