### ISSUE TITLE
Some pokemon are not showing up like pigey and rattata.

### ISSUE THREAD

**Issue by KiraEnishi** [istornz/iPokeGo#32]
Like Title says I toggle the hide common on and off yet theses pokemon do not show up. They do show up on the web browser but not within the app.

**Comment by KiraEnishi** [comment]
Zubat and Weddle are also not showing up.

**Comment by jankcat** [comment]
Seconded. Seeing same issue.

**Comment by Yedion** [comment]
Same issue here

**Comment by istornz** [comment]
Hello this is normal.
The feature "Hide very common" feature is currently in developement and it's activated by default.

Here is the current list of blocked pokemons :   
- Rattata
- Pidgey
- Zubat
- Drowzee

This list is to test and with the future version you will be able to change them. 
PS: You can see in France there is a LOT of Rattata, Pidgey, Zubat and Drowzee :p

**Comment by istornz** [comment]
See #3  "showing up are a bit wonky"

**Comment by istornz** [comment]
This functionality is now working.
