### ISSUE TITLE
[feature request] IV and moveset information

### ISSUE THREAD

**Issue by mlc130104** [istornz/iPokeGo#322]
With a new PR in pokemongo-map (https://github.com/PokemonGoMap/PokemonGo-Map/pull/1272), IV and moveset data are now available in the web interface as well as in /raw_data. I would like to know if iPokeGo could implement this.

**Comment by istornz** [comment]
When this great feature will be available, I think to remove the "disappear" label on the annotation (you can add the timer it's more useful). What do you think ?

**Comment by cyan** [comment]
heya,
i think, you should add the iv% behind the pokemon name and instead of the disappear label, show the move set (wich sometimes change everything from running like bolt to "keep sleeping its a trash" xD)

**Comment by toshioson** [comment]
This feature is much wanted, hope it can be implemented soon in iPokeGo!

Besides showing, next step could be to add also as filter for showing the Pokemon if possible?

**Comment by mbg032373** [comment]
This PR has been merged.  Getting this information into iPokeGo and the ability to sort and get notifications based on IV would be great!

**Comment by SnakeIz** [comment]
May we please get the display of the IVs and move sets added to ipokego?

**Comment by SnakeIz** [comment]
Also, include the IV/moves in the push notification.

**Comment by istornz** [comment]
Now implemented !
Have fun guys ;)

**Comment by SnakeIz** [comment]
Awesome, thank you! 

But can we also have the move set? Important when deciding on chasing a lower CP final evolved pokemon or if time left is short.

**Comment by mbg032373** [comment]
Hopefully, you can get around to filtering and notifications based on a specified IV% at some point.

Thanks for the great work!

**Comment by istornz** [comment]
@SnakeIz Yeah coming soon ! (I have already added these infos in the db 👍 )
@mbg032373 Feature coming in a few hour. I set the IV% point at >= 70% tell me if it's correct :)

**Comment by istornz** [comment]
@mbg032373 Last commit add Push support for high IV Pokemon only

**Comment by SnakeIz** [comment]
I would allow the user to set the IV percentages for those features

**Comment by mbg032373** [comment]
Yes, user set would be best.

**Comment by SnakeIz** [comment]
Have an issue with the IV percent that shows. They are incorrect. Earlier tonight I had an eevee that was left 91.1. After that when multiple eevees spawned it still showed 91.1, triggered a notification, but the actual IVs it displayed clearly showed it was not 91.1. What was caught was the IVs that displayed, which again were not 91.1. Bit later there was a legit 71% that spawned and now one that spawned shows 71% but the IVs it shows are 3/1/3.

**Comment by istornz** [comment]
@mbg032373 Now you can set your custom high IV in settings.
@SnakeIz I think it's patched now, can you test again and see if all IVs are correct ?

**Comment by toshioson** [comment]
@istornz how to compile the latest version including this feature into an iPA? or where can I download one for trial? thanks!

**Comment by istornz** [comment]
@toshioson Enjoy ! https://github.com/istornz/iPokeGo/releases/tag/V2.4

**Comment by mlc130104** [comment]
The new threshold (80%) is nice enough, tho IIRC the wonder appraisal happens when total IV > 82%.

**Comment by toshioson** [comment]
@istornz I sideloaded the IPA file onto my iPhone, trusted in device management but it won't start. Removed and sideload again does not help. Tried on another iPhone and got the same problem. Is it my problem?

**Comment by congbosun** [comment]
@istornz @toshioson I got the sam problem!

**Comment by kallik** [comment]
Hi, first off, love the app!

I noticed when a pokemon appears with the "hot_pokemon" image overlay that pokemon appears "hot" next time it spawns whatever iv that pokemon might have. Maybe because of the reuse logic in PokemonAnnotationView init function. I patched it temporarily by colring the time-left tag red for hot pokemons.

**Comment by istornz** [comment]
PokeGO V2.4 is now available on the AppStore :+1: 
https://itunes.apple.com/us/app/ipokego-for-pokemon-go/id1138277066?l=fr&ls=1&mt=8
