### ISSUE TITLE
App isn't working 

### ISSUE THREAD

**Issue by Solo-Rider** [istornz/iPokeGo#324]
Nothing is being shown on my radar although there are things nearby on Pokemon Go

**Comment by MikeMilzz** [comment]
I'm seeing same behavior. If I look at the webpage for my PokemonGoMap server, I will see stops, gyms, and spawns. When looking at the app, I only see gyms and stops. This was working fine until I updated to the latest version of iPokeGo (which I did after updating to the latest server version of PokemonGoMap server, so could be related).

**Comment by TheNewDarkOne** [comment]
Is your server throwing errors like mine?
https://github.com/istornz/iPokeGo/issues/323

**Comment by istornz** [comment]
@MikeMilzz @TheNewDarkOne What is your PokemonGO Map version ?

**Comment by TheNewDarkOne** [comment]
I use latest dev, always. development branch latest checkout

**Comment by istornz** [comment]
@TheNewDarkOne  Oh ok, I'm waiting for the official release to support the new version (To avoid having to review everything)

**Comment by istornz** [comment]
So I close this issue (please use this issue now : #323)
