### ISSUE TITLE
iPokeGo expires every week

### ISSUE THREAD

**Issue by toshioson** [istornz/iPokeGo#330]
First of all, thanks to the great works of making this app, the map is really handy and useful!

I have a persistent problem, the iPokeGo I sideloaded using the instruction of this guide got expired (app would not open) about a week every time and I have to reload it again to use it which makes it very inconvenient especially when I am outside wanted to use this app. From reddit I learnt it is probably because the provisioning profile has expired.

Any permanent solution or at least extend the "valid period" of the app? Thanks!

**Comment by robiningelbrecht** [comment]
I don't think this is possible because your Iphone does recognize this app as an "developer app"...

**Comment by istornz** [comment]
Hello, I have some great news !
iPokeGO is officially available on the AppStore right now ! : https://itunes.apple.com/us/app/ipokego-for-pokemon-go/id1138277066?l=fr&ls=1&mt=8
