### ISSUE TITLE
2.4 beta

### ISSUE THREAD

**Issue by TRingo1** [istornz/iPokeGo#333]
@istornz  nice job with the new feature -enc  just update my map-server and the latest 2.4 code, recompiled and really like the new IV addition to your app! Great work!

**Comment by istornz** [comment]
@TRingo1 Thanks a lot 👍

**Comment by BladeBorn345** [comment]
How do I update???

**Comment by BladeBorn345** [comment]
@istornz Can you explain to me how to update my code to 2.4? or @TRingo1 If you have time?

**Comment by istornz** [comment]
PokeGO V2.4 is now available on the AppStore :+1: 
https://itunes.apple.com/us/app/ipokego-for-pokemon-go/id1138277066?l=fr&ls=1&mt=8
