### ISSUE TITLE
Wont open

### ISSUE THREAD

**Issue by gigiknappe** [istornz/iPokeGo#334]
I see that you added "Wait a little bit...After a moment, the app is installed on your device but you cant run it" 
I have waited over an hour continuously opening and having the app force close obviously while going to settings - general - profiles, and not seeing any new profiles show up for me to trust. 
iOS8.4

**Comment by istornz** [comment]
I think the method to install the IPA (sideloading method) is not working on iOS 8...
Please test installing an older version and say me if you can run it please.

**Comment by gigiknappe** [comment]
Yes, I am able to run v2.3 without any issue. Tried on iOS 9.3 last night and that did not work either. 

Thanks in advance man

**Comment by istornz** [comment]
PokeGO V2.4 is now available on the AppStore :+1: 
https://itunes.apple.com/us/app/ipokego-for-pokemon-go/id1138277066?l=fr&ls=1&mt=8
