### ISSUE TITLE
v2.4 Beta 1 Launching Issue

### ISSUE THREAD

**Issue by koki871** [istornz/iPokeGo#335]
Hi, I downloaded the beta version on my iPad Air (iOS 9.3.5) but after trusting the device, it does not launch at all. Should I upgrade the software to iOS 10? Or is it working only on iPhones? Thanks!

**Comment by intopuddles** [comment]
Not working on iPhone either.

**Comment by TRingo1** [comment]
Not sure why it's not working for you   It is working on my iphone6 iOS 10.02.

**Comment by jorgitoh** [comment]
Not working. Iphone 6s IOS 10.

**Comment by skosi123** [comment]
Not working. Iphone SE IOS 10

**Comment by istornz** [comment]
I think there is a problem in the IPA package...
Someone can test compiling and run the app with Xcode ?

**Comment by robiningelbrecht** [comment]
I can confirm this problem

**Comment by istornz** [comment]
PokeGO V2.4 is now available on the AppStore :+1: 
https://itunes.apple.com/us/app/ipokego-for-pokemon-go/id1138277066?l=fr&ls=1&mt=8
