### ISSUE TITLE
PokemonGo-Map works with IOS Browser but not with iPokego IOS App

### ISSUE THREAD

**Issue by flame4ever** [istornz/iPokeGo#336]
Hello everybody,

with the Safari Browser and IPhone 6s my PokemonGo-Map (own Server and over HTTPS://) it's working well.
Now i have seen that there exists the iPokeGo App in the Appstore, but when i add my https://xxx.net:5000 Server, it only shows the map but no Pokemon, Pokestops or Gyms.
My server has no Password, so i just entered the Servername (anyname) and Server (https://xxx.net:5000) in the Config >Server > Add mask.
Do i Something wrong?

**Comment by istornz** [comment]
Hello, what is your Pokemon GO Map version ?
What is the color of the loading in the status bar ?

**Comment by flame4ever** [comment]
1. The actual https://github.com/PokemonGoMap/PokemonGo-Map develop branch
2. orange

**Comment by istornz** [comment]
Do you use v2.4 ?

**Comment by flame4ever** [comment]
do you need more infromations?

**Comment by flame4ever** [comment]
No v2.3 from the AppStore

**Comment by istornz** [comment]
v2.3 is not compatible with Pokemon GO Map (develop branch).
Use v2.4 for your Pokemon GO Map dev branch

**Comment by flame4ever** [comment]
ok thx.
do you know, when the Version 2.4 will be released in the appstore?

**Comment by flame4ever** [comment]
now i have installed v2.4 with xcode on my iphone  but it do not work as well.

**Comment by istornz** [comment]
@flame4ever Orange bar too ?

**Comment by flame4ever** [comment]
Yes orange too.

**Comment by TheNewDarkOne** [comment]
@flame4ever Try turning spawn points off if they are enabled (do it before connecting to server) and see what it does?

**Comment by istornz** [comment]
PokeGO V2.4 is now available on the AppStore :+1: 
https://itunes.apple.com/us/app/ipokego-for-pokemon-go/id1138277066?l=fr&ls=1&mt=8

**Comment by istornz** [comment]
Please test with the latest version. 
If it's not working too, please open a new issue ;)
