### ISSUE TITLE
Gen 2 Support

### ISSUE THREAD

**Issue by TheNewDarkOne** [istornz/iPokeGo#349]
It kinda works if using text/themeless but can't use any filters or it stops working. hide common? hides common AND all gen 2, etc. so no filter, text theme to do gen 2

what needs though is images for gen 2 in themes, and filters to add support for handling up to 250.

**Comment by TheNewDarkOne** [comment]
I was able to fix the theme problem myself. I just added images for pokemon 152-650 for good measure and app uses them just fine. All that remains is filter updates though so I can filter commons again without it filtering ALL gen 2

**Comment by johnforeland** [comment]
I tried making a theme, but my icons keep blinking 😨 
Would you mind sharing the zip?

**Comment by thedruid** [comment]
replace in global.h:
#define POKEMON_NUMBER      155

with:
#define POKEMON_NUMBER      255

and filter option is working again.

**Comment by TheNewDarkOne** [comment]
I mean building from source sure, but the source is currently behind app store version. :\

**Comment by istornz** [comment]
@TheNewDarkOne Can you share with me your theme plz ?
I will made a new update for full support

**Comment by TheNewDarkOne** [comment]
Honestly I took the updated sprites from rocketmap and used those for personal use. I'm sure to include em in this though you should probably reach out to @sebastienvercammen who put the time into making them all.

**Comment by Alderon86** [comment]
@istornz This is important! Please hurry up i need this lovely notifications for new mons :D

**Comment by istornz** [comment]
@Alderon86 I'm sick so I will do that ASAP.

**Comment by jorgitoh** [comment]
@istornz Hi, you ill update the ipa / source for 2gen pokemons?. Thank you for ur work :)

**Comment by istornz** [comment]
@jorgitoh IPA & AppStore version 👍

**Comment by decsiteru** [comment]
@istornz hi is it possible to add the moveset support at the same time when clicking on the 'mon plz?

**Comment by TheNewDarkOne** [comment]
One step at a time, i'd rather him just get the media/filters updated first, worry about features later.

**Comment by istornz** [comment]
Anyone can test the new version with latest theme (don't have server to test) : https://github.com/istornz/iPokeGo/wiki/Centralization-of-all-downloadable-theme#official-rocketmap-theme

If it's ok I will publish a version on the AppStore 👍 
Waiting for reply :)

**Comment by johnforeland** [comment]
Does that version support themes, though? Can't find it in the settings.

**Comment by TheNewDarkOne** [comment]
I didn't test newest version since i only run app store version. however using app store version i downloaded that theme and the theme itself is fine. of course no filters cause it's app store version. 

hope that helps!
![img_1334](https://cloud.githubusercontent.com/assets/21180727/23280607/d8029ab6-f9e7-11e6-8d36-8ee8489c3afd.PNG)

**Comment by decsiteru** [comment]
Can you upload an ipa to test it out? Sry I don't have a mac so i can't compile

**Comment by k9ordon** [comment]
im also missing the themes settings :(
![img_2017-02-24 12 31 50](https://cloud.githubusercontent.com/assets/102591/23302056/51a85bc6-fa8d-11e6-99f1-bda137403f86.jpg)

**Comment by TheNewDarkOne** [comment]
Far as I know the themes stuff was never merged into this branch. a few features appeared only in app store version which is why I stopped using source version.

**Comment by johnforeland** [comment]
Okay, but to answer your question, @istornz, everything works (ish). **AppStore version** ([screenshot](http://i.imgur.com/fhI3DXi.png)) works perfectly with the RocketMap sprites (albeit without filtering)

**GitHub version** ([screenshot](http://i.imgur.com/bCJFUv4.png)) works with gen 2, because I added notifications for some gen 2 commons and it took me to the location in the screenshot with no Pokèmon (because no gen 2 sprites in GitHub version). See both screenshots, same area, proving Github version works with gen 2 now, just without any sprites.

So, App Store version (with themes) just needs the following, as mentioned by @thedruid:
`#define POKEMON_NUMBER 251` (Not 255 though, because 252-255 is only glitch Pokèmon and eggs, see [screenshot](http://i.imgur.com/yJyu4Sr.png).

**Comment by johnforeland** [comment]
I created a [gen 2 support PR](https://github.com/istornz/iPokeGo/pull/350), if anyone wants it before an AppStore version is made / accepted by Apple. It contains new gen 1 and 2 sprites, and reduced number of Pokémon from 255 to 251. [Before and after screenshot](http://i.imgur.com/v8wJy3t.png). (Pidgey and Spinarak hidden by filter, to name a few)

**Comment by istornz** [comment]
Hi sorry guys I have forgotten to include the theme support 👎 
Now this functionality is open-sourced !

@johnforeland Thanks for your PR, but I need to remove all copyrighted image from this repo 🤐 
Can anyone test this new version ?

I will submit the AppStore version today !

**Comment by istornz** [comment]
Version 2.5.1 submitted to the AppStore 👍

**Comment by TheNewDarkOne** [comment]
i did a clean build and tested all day, was good with rocketmap theme. filters and all were perfect

**Comment by istornz** [comment]
@TheNewDarkOne Okay thanks for your reply, I close this issue 👍
