### ISSUE TITLE
Icons warped on 3.5 inch display

### ISSUE THREAD

**Issue by jankcat** [istornz/iPokeGo#35]
As seen in the attached image, the icons are warped on 3.5 inch displays. This may block the App Review process, and hinders the experience for iphone 4s users (which can use up to iOS9).

![500x500bb](https://cloud.githubusercontent.com/assets/7744158/17128651/90f00a96-52cb-11e6-9903-72104e76afd3.jpg)

**Comment by istornz** [comment]
Hum I don't have this bug with the 4S simulator so I can't try to fix that now :/

**Comment by DesuCat** [comment]
I have the same problem on my iPhone 5(ios 8.1)
And the same problem on 8.1 iPhone 5 simulator in xcode:
<img width="322" alt="screen" src="https://cloud.githubusercontent.com/assets/20663240/17139678/23a62000-534e-11e6-95e7-53811762d4f9.png">

**Comment by jankcat** [comment]
Ahh must be 8.1. I used 4s on 8.1. @istornz what ios is your 4s emu?

**Comment by istornz** [comment]
@jankcat iOS 9, so it's on iOS 8...

**Comment by jankcat** [comment]
Yup. Tested on 8.4 and it looks fine. 8.1 issue it seems.

![simulator screen shot jul 26 2016 9 30 02 am](https://cloud.githubusercontent.com/assets/7744158/17144332/9f7cf734-5313-11e6-8546-623dcec5f5e4.png)
![simulator screen shot jul 26 2016 9 29 58 am](https://cloud.githubusercontent.com/assets/7744158/17144336/a1bf0776-5313-11e6-92dd-66a5634cfd48.png)

**Comment by jankcat** [comment]
Issue with out of date OS, users should be advised to use patched OS.
