### ISSUE TITLE
Full control address commit broke app

### ISSUE THREAD

**Issue by fraannk** [istornz/iPokeGo#38]
The latest commit "Full control address" broke all of it. If I put http:// back it works again.

**Comment by istornz** [comment]
Yeah it's normal :)
This commit permit user to set protocol (like http or https)

**Comment by fraannk** [comment]
Oh, so I'll have to type it myself? Cool. In that case the placeholder text should be changed to http://example.com:5000 or something :)

**Comment by istornz** [comment]
Yes I'm gonna to change that !
Thx
