### ISSUE TITLE
Opening and closing settings menu makes set location (green pin) go bonkers

### ISSUE THREAD

**Issue by fraannk** [istornz/iPokeGo#40]
Opening and closing settings menu makes set location (green pin) go bonkers. The animation adds onto itself every time you've been in the settings. [Image](https://s3.amazonaws.com/f.cl.ly/items/3Y030k3n3G0b401k101B/IMG_0626.jpg)
I think it's adding more green pins on top of each other since the shadow is stronger as well.

**Comment by istornz** [comment]
Now fixed thx for the report

**Comment by fraannk** [comment]
Do you have a discord I can talk to you on? So I won't keep spamming issues :D
