### ISSUE TITLE
Pokemon don't show up

### ISSUE THREAD

**Issue by mrik974** [istornz/iPokeGo#42]
I Installed a Pokemongo-Map server on the web. Server is up and running, tested using a browser,  totally accessible and not protected (for now) so I won't leave its address here.
I built the app using Xcode 7.3.1 instead of 8 beta. the app building went OK
I run iOS 9.3.2 on a 64GB iPhone 6. 
I launched the app with and without debug.
With debug I saw lines like "Pokemon added on map Piafabec" or "Pokemon removed Krabby" (yup, I'm a frenchie).
But there was nothing appearing on the map. Have I done anything wrong?

**Comment by istornz** [comment]
Salut, je te propose qu'on parle en français c'est plus simple hein :p
Possède-tu la version 2.0 du serveur ?
Quand tu touche la notification "Pokemon added on map Piafabec", est tu redirigé sur la carte ?

**Comment by ZihanTang** [comment]
For me, the log just show as bellow. No pokemon showed up.
![screen shot 2016-07-26 at 11 51 12 am](https://cloud.githubusercontent.com/assets/12687471/17145209/5f6b364c-5327-11e6-9c84-4fd7bc78cc37.png)

**Comment by istornz** [comment]
@ZihanTang Have you entered the address of the server correctly with "http://" ?

**Comment by ZihanTang** [comment]
@istornz I entered the address correctly with its url.
http://pokemap-eric.herokuapp.com
The site works through directly visit via browser.

**Comment by mrik974** [comment]
istornz, thank you for your answer :). Je vais continuer à parler en anglais pour que ça profite à tout le monde, qu'en penses-tu ? :)

I just pulled the server and built it with its `Dockerfile`.
I pulled the server from this address : `https://github.com/AHAAAAAAA/PokemonGo-Map`
The package.json file shows `version 0.1.0` so I don't know if I'm running version 2. 

But I think I understand the problem. 
The server is set to find Pokémon in `Toulouse, France`. My iOS app actually locates me in `Cornebarrieu, France`. When I tapped on the notification, the map moved to Toulouse, where Pokémon were shown.

Isn't there a way to show Pokémon only where I'm truly located ?

**Comment by istornz** [comment]
Hello i entered exactly the same url and it's work perfectly.
"http://pokemap-eric.herokuapp.com". Check spelling mistake and try with the latest version of the app.

**Comment by ZihanTang** [comment]
Thanks.. After reinstalling latest version, pokemon started showing up but I can't set location...

**Comment by mattrat88** [comment]
after update pokemon are not showing up also cannot choose location remotely anymore press and hold will not communicate with server anymore how do i get the previous version

**Comment by istornz** [comment]
@mattrat88 Do you have the V2 of the server (https://github.com/AHAAAAAAA/PokemonGo-Map/tree/V2.0) ?

**Comment by mattrat88** [comment]
The one I can select Pokemon to filter out ? I thinks that's v2

**Comment by pain2589** [comment]
Hello, i deployed successfully with heroku, but when i try it, no pokemon, pokestop, pokegym in the map? Did this server include databse for pokemon, pokestop, pokegym?pokemon, pokestop, pokegym

**Comment by pain2589** [comment]
Hello, i test my server heroku, it showed pokemon, stop & gym. But in the app, it can not show up :(

**Comment by mattrat88** [comment]
https://
