### ISSUE TITLE
Common pokemon not showing up regardless of setting

### ISSUE THREAD

**Issue by nardavin** [istornz/iPokeGo#43]
As of the new update, common pokemon do not show up despite how I change the setting. They appear fine on the browser client. If you need more info (not sure what is needed), just let me know.

**Comment by fraannk** [comment]
Works fine here.

**Comment by nardavin** [comment]
It is not working as of the pokestop fix update. I just saw the ipad compatibility update, and I will try to download that one and see if it works.

**Comment by istornz** [comment]
@nardavin Do you use V2.0 server ?
It's work fine for me (Hide Common on/off)

**Comment by istornz** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/tree/V2.0

**Comment by nardavin** [comment]
Closed. Fixed by updating to latest version.
