### ISSUE TITLE
"Real" Notice?

### ISSUE THREAD

**Issue by AndreasEnemyr** [istornz/iPokeGo#46]
Are you going to do so when a pokemon in the favorite you get a real push notice and not just a notice in the app? Would love that, otherwise good app :)

**Comment by hthompso** [comment]
I second this, just downloaded and setup today. Wish I had more coding experience to help, but I'd love this feature. Thanks for all your hard work!

**Comment by istornz** [comment]
This functionality is now online with the new version of the app :)
