### ISSUE TITLE
IPA or DEB File for Jailbroken Devices

### ISSUE THREAD

**Issue by omidzargham** [istornz/iPokeGo#50]
Can someone please create an IPA or DEB file for jailbroken phones? I don't have a mac to install xcode. There is another iOS pokescanner like this at https://github.com/ruffnecktsk/pokemap_live_ios that has an IPA file and it worked fine for me so I know its possible...Thanks!

**Comment by istornz** [comment]
I uploaded an iPA file of the latest version of the app.
I don't have any iDevice Jailbroken so can you try to install it ?

**Comment by istornz** [comment]
I also added a deb file.

**Comment by omidzargham** [comment]
I couldn't install either of them.. forget about the deb file. I dont think that will work. The app crashes on opening after installing the IPA, I think this means the code-signing is not proper. I don't know if you know how to make this work or not, its not a big deal if you can't. I guess us non mac users can borrow a mac from a friend to make it work, thanks man

**Comment by istornz** [comment]
I know how to bypass code-signing but you need a Jailbroken device to run Clutch on it...

**Comment by kabeern** [comment]
Hi, i have a jailbroken iphone and would like to install this. How can I use clutch to install it?
Thanks

**Comment by fatherofawesome** [comment]
Please google the new code signing tool from "Saurik". I have successfully sideloaded this using that. It requires an apple account.

**Comment by AppleTechy** [comment]
I used App Sync Unified and IPA Installer and successfully got it to show on the home screen(using the iOS V2 file) but when I went to open the app is says "this beta is expired" @omidzargham Do you have any ideas?

**Comment by omidzargham** [comment]
@AppleTechy forget all that app sync stuff. Just follow the new readme's instructions using cydia impactor. worked for me. Also that "beta expired" message came up for me when I lost my jailbreak for rebooting my device, since the newest jailbreak is semi-tethered. Try rejailbreaking. and following the new instructions with cydia impactor. By the way thanks @istornz cause it works!!

**Comment by AppleTechy** [comment]
@omidzargham I was in jailbreak "mode" when I got that "beta expired" message. If I side load via Cydia impactor will I have to reload it every 7 days since I currently don't pay the $99 for a Developer account?

**Comment by AppleTechy** [comment]
I believe the issue I am running into("beta expired") had something to do with how the IPA was created as I have been successful in downloading other ipa files with a successful install an running process. Doing nothing different than I did for iPokeGo

**Comment by istornz** [comment]
Try this plz : https://github.com/istornz/iPokeGo/wiki/Installing-iPokeGO-with-any-computer-(Windows,-Mac-and-Linux)-easily-!

**Comment by istornz** [comment]
There is a new IPA file, try to download it and install it with AppSync

**Comment by peacefulreason** [comment]
If it's the v2 from yesterday, the same thing is occurring. None of the ipas install with AppSync, and the deb will not install either.

**Comment by ducnguyen1806** [comment]
I have tried installing 2.0.1 and it still says Beta Expired.

**Comment by istornz** [comment]
If someone can install the IPA file with Impactor and run Clutch or any script like this to bypass code sign It would be appreciable :)

**Comment by AppleTechy** [comment]
I installed it with impactor just fine. Now have to wait the 7 days to see
if it expires or if App Sync will bypass the limit

**Comment by kabeern** [comment]
@peacefulreason ; tried the DEB alone. (installed on iphone 6 ios9.0 using iFile installer. It is showing as installed in Cydia, but no icon appears on my iphone homescreens?

Was i meant to install both the IPA and DEB at the same time?
Thanks

**Comment by peacefulreason** [comment]
@kabeern  You have to respring after. I had to respring twice actually. I assume the uicache isn't being cleared. It will pop up if you do this. I had the same thing happen. No need to install the IPA.

**Comment by tyt11123** [comment]
@peacefulreason ; Can you tell me how to create the working deb? Just want one for 2.2

**Comment by peacefulreason** [comment]
@tyt11123 Sorry, I didn't see this comment. If memory servers me, I sideloaded the IPA, copied the folder into the proper folder structure for DEBs, and created the control file, then ran DPKG on the folder.

**Comment by istornz** [comment]
I close this issue.
iPokeGO is now available for all in the AppStore : https://itunes.apple.com/us/app/ipokego-for-pokemon-go/id1138277066?l=fr&ls=1&mt=8
