### ISSUE TITLE
cannot long press to change location and pokemon not showing up 

### ISSUE THREAD

**Issue by mattrat88** [istornz/iPokeGo#52]
happend after updating to newest version

**Comment by RubikOfAstora** [comment]
Same here, since the last update no pokemons are showing up.

**Comment by hoangnn89** [comment]
It does show on simulator but device.

**Comment by mattrat88** [comment]
I'm using forward is that an issue ?

**Comment by Yedion** [comment]
I´ve got the same problem. Server ist running on OSX 11.11.6 and the app on an iPhone6 with iOS 10 dev beta 3

**Comment by istornz** [comment]
Have you installed the V2 of the server (https://github.com/AHAAAAAAA/PokemonGo-Map/tree/V2.0) ?

**Comment by Yedion** [comment]
I´m using the dev version of the server. The app worked with the server before the update

**Comment by istornz** [comment]
I just tested with the dev version and it works perfectly (pokemon appear and I can change location).
Do you launch your server with arg "-H 0.0.0.0" and put the ip address on network ?

**Comment by Yedion** [comment]
It is working again. I just had to add the prefix "http://" to the server address. Haven´t used it before and it was working until the update

**Comment by mattrat88** [comment]
Lol well don't I feel like a dumb bunny lol , it's back up and working the only error was my not adding http:// to my server address , your apps on point a thousand thank yous my friend
