### ISSUE TITLE
Not an Issue, but Video Tutorial I made.

### ISSUE THREAD

**Issue by Azzivo** [istornz/iPokeGo#53]
Not too sure how to contact the owner. Fairly new to GitHub. Maybe he can add it to the description page under installation as a Video Guide. There's no voice, just caption'ed and steps shown.

https://www.youtube.com/watch?v=DxredLkZ8hI

Made a video tutorial on how to install iPokeGo, it's a 2 part series, where I'll teach people how to setup a server in part 2.

**Comment by istornz** [comment]
Nice !

**Comment by Azzivo** [comment]
Would you be willing to add it to your Github iPokeGo page? If not I can remake a new tutorial with voice if you'd like.

But the tutorial itself is simple and fast.

**Comment by istornz** [comment]
Your video is now referenced in the wiki thx, I close the issue.
