### ISSUE TITLE
I can´t configure server :(

### ISSUE THREAD

**Issue by gilrodar** [istornz/iPokeGo#57]
Hello! the app run in my phone not problem but y can´t configure server for search pokemons. 
Just show me my location.   

**Sorry for my English :)**

**Comment by istornz** [comment]
Have you installed the V2 of the server ? (https://github.com/AHAAAAAAA/PokemonGo-Map/tree/V2.0)

**Comment by gilrodar** [comment]
Yes and i configure the server of this form.

http://127.0.0.1:5000

But not load nothing..

**Comment by istornz** [comment]
http://127.0.0.1:5000 is your computer in local not in network.
Do you launch your server with "-H 0.0.0.0" and set you local ip address like "http://192.168.1.14:5000" ?

**Comment by diepflanzen** [comment]
Strangely, -H 0.0.0.0 and ip settings "http://192.168.2.8:5000" does not work from home.
but my office IP worked....

**Comment by hthompso** [comment]
Could it be an ISP restriction? I had a similar problem earlier, but ended up using ngrok (https://ngrok.com/) to open a tunnel from my local host. I plugged the new ngrok url in the app and it worked like a charm.

**Comment by diepflanzen** [comment]
You're right! Thanks a lot! ngrok works great~
