### ISSUE TITLE
XCode version

### ISSUE THREAD

**Issue by Clowning** [istornz/iPokeGo#6]
An issue just to say that sad because we need to have XCode 8 and it's a beta IDE :/ !

**Comment by areteCocoa** [comment]
Has anyone tried to install with Xcode 7?

**Comment by istornz** [comment]
I think it may work with Xcode 7. If anyone want to test :)

**Comment by blackhattristar** [comment]
@istornz @Clowning @areteCocoa I have! It does work with Xcode 7. All you have to do is click on Storyboard, make sure you're under File Inspector, then under Interface Builder Document change "Opens in" to Xcode 7.0

Do this for both the Storyboard and the Launch Screen, close and reopen the application. I hope this helps! :)

**Comment by Clowning** [comment]
I has try with XCode 7 yesterday but i have this error : 

In file LaunchScreen.storyboard : 
The document "(null)" requires Xcode 8.0 or later.

**Comment by jankcat** [comment]
@Clowning try this PR: https://github.com/istornz/iPokeGo/pull/33
