### ISSUE TITLE
Change Location Starts Scan On Long Press

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#65]
I'm not sure if this is a bug per say but I just noticed within the recent updates that when I touch and hold down on the map (long press), the map automatically starts scanning that area for Pokémon. I thought in the previous versions you had to long press somewhere on the map and then hit the scanner button. Is this a bug or just a new feature so that you only have to long press on the map to start scanning as a new location? You no longer have to press the scan button?

**Comment by istornz** [comment]
There are no new function simply long press on map to launch scan :)

**Comment by blackhattristar** [comment]
@istornz Awesome! So no need for the scanner button? Does the scanner button still work / do anything? :D

**Comment by mostafaelhefnawy** [comment]
@blackhattristar the scanner button is for you to automatically position the spot to the middle of the screen. Just like what happens when you click the "my location" button
