### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#7]
Every time a Pokémon appears the mp3 notification goes off and a little black notification bar at the top appears. I would suggest to change this to appearing only when a favorite Pokémon is near by. If it happens every time a Pokémon appears, not only is it annoying but it slows down the whole app to a crawl.

The notifications actually shut down my phone and forced a reboot.

**Comment by areteCocoa** [comment]
Could we filter which pokemon get a notification?

**Comment by blackhattristar** [comment]
@areteCocoa Are you having issues with the notifications as well?

**Comment by istornz** [comment]
Now you can enable/disable fav or normal notification :)
Thx for your report
