### ISSUE TITLE
Multi account authentication support?

### ISSUE THREAD

**Issue by hoangnn89** [istornz/iPokeGo#72]
Is it in the road map?

**Comment by istornz** [comment]
What do you want to say about "Multi account" ? PTC/Google account or server ?

**Comment by Sweetfire37** [comment]
Pourrions-nous accélérer le scan de la zone avec plusieurs serveurs ?

**Comment by Schwaitz** [comment]
What does this mean, @hoangnn89? I just downloaded and installed today, but the only "authentication" that I've seen is from the hosted server. What do you mean by, "multi account authentication support"?

If you mean having various different accounts add pokemon to the same database, that can be done through the main server. Just have multiple servers running, all pointing towards the same database. Use the -D flag for this.

i.e: `python runserver.py -st 5 -l "New York, New York", -D DatabaseName.db`

You could also run multiple servers, and not flag -D, as they will all point towards the default of pogom.db. See more [here](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Command-Line-Arguments).
