### ISSUE TITLE
Feature Request: Push Notifications 

### ISSUE THREAD

**Issue by SrGMC** [istornz/iPokeGo#78]
It would be nice if the app had push notifications. It could use third-party apps like OneSignal, or maybe a tutorial on how to setup notifications in Xcode

**Comment by Enterodactyl** [comment]
To add on to what you said, I think it would be great if there were 2 types of notifications.

1. Notification when a Pokemon you favorited shows up.

2. Notification when a Pokemon appears within your specific location, irregardless if it's common or not.

I find that while I don't want to see any common pokemon on my map, I would still like to catch them if they happen to spawn right on top of me. It would be a similar feature to what the Pokemon Go Pro bracelet would do.

**Comment by istornz** [comment]
Yeah it's a good idea, I'm working on it.

**Comment by blg-andreasbraun** [comment]
Do you want to implement remote push notifications or local push notifications?

Isn't the current state right now that the app is not running in the background? In that case there is no chance to setup a local notification, because the only situation a user would get one is when he/she actually is looking at the device.

Maybe a background mode is needed for this as well?

**Comment by istornz** [comment]
Using remote push notifications was my first idea but you need a dev account and a custom server so it's not a very good idea.
I'm going to work on local push notification and so background mode.

**Comment by istornz** [comment]
@blg-andreasbraun I completed the development of real notif. It works very great !!
I put it online tonight 👍

**Comment by SrGMC** [comment]
@istornz That's great! I'll try it later, if not tomorrow.
I'll tell you if I find any bugs or any improvements you could make

**Comment by istornz** [comment]
Now online :)

**Comment by michaelowens** [comment]
This doesn't seem to work for me for favorites. I saw a Voltorb show up that was on the favorites list, but no notification. If I choose "normal notifications" it will send push notifications every 5 seconds with pidgeys. So it seems to work for normal, but not for favorites for me. I didn't add any favorites myself, just used the predetermined list.
