### ISSUE TITLE
Error: Impossible to make the request

### ISSUE THREAD

**Issue by mitchlanglois** [istornz/iPokeGo#8]
I get this error popup as soon as I open the app. The app shows a map and can find my location, but will not populate pokemon.

Do we have to setup credentials for the app? Or log in?

**Comment by areteCocoa** [comment]
You need to have a server that gets the map of pokemon -- this app does not do the actual queries itself, it is only a client.

**Comment by mitchlanglois** [comment]
Where do I configure it to point to my server? Not familiar with iOS development

**Comment by areteCocoa** [comment]
The configuration is in the actual app itself, not in Xcode.
