### ISSUE TITLE
PokemonGo-Map V2.0 Gone?

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#82]
I can't seem to find https://github.com/AHAAAAAAA/PokemonGo-Map/tree/V2.0

Is this the one we should be using? https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by philipp-r** [comment]
<https://github.com/AHAAAAAAA/PokemonGo-Map/tree/v2.0.0>

**Comment by blackhattristar** [comment]
@philipp-r Thank you :)
