### ISSUE TITLE
Change scan location does not work

### ISSUE THREAD

**Issue by peter4k** [istornz/iPokeGo#88]
Thanks for the great work, the app looks fancy.
However I am not able to change my scan location. After I long press a location on the map, the server is still scanning the position I set on my browser, and only pokemons around this position will appear in the ios app.

Some configurations issue? thanks!

**Comment by istornz** [comment]
Hello, do you have the latest version of the server installed ? (V2)

**Comment by peter4k** [comment]
I have v2.1.0 server deployed. 
By tailing the log, I figured out that after changing scan location in the web version, its sending a request:
````
at=info method=GET path="/next_loc?lat=37.560465&lon=-122.251286"
````

But I did not see the server received this request after setting a new scan location in iOS app.

It this a new API in 2.1.0 they used? so that the iOS version is not supporting server v2.1.0?

**Comment by istornz** [comment]
Works great for me with v2.1.0 ...
Do you have installed latest version of the iOS app ?

**Comment by xphongvn** [comment]
@peter4k works great for me too, for server v2.1.0

To scan in a new location, you need to press down the screen to the new location and press the search icon.

**Comment by istornz** [comment]
I close the issue, please create a new one if problem persist.
