### ISSUE TITLE
Run app from heroku server?

### ISSUE THREAD

**Issue by theebanka** [istornz/iPokeGo#89]
I have been running (successfully) a heroku server for the last few days without any issues. Does the app not allow heroku addresses in the server spot? When I put my URL in Pokémon, pokestops, and gyms don't show up... am I missing a step or something?

**Comment by istornz** [comment]
It's work for me with an heroku server. Put "https://" (note the 's' for httpS) before the server address.

**Comment by theebanka** [comment]
Huh that's the strangest thing! Even with the https I still am not seeing anything... might mess with it more later this evening! Thanks for the help though

**Comment by theebanka** [comment]
And all of a sudden it just started working! Thank you!!! 

Now how do you change the location it's searching?

**Comment by mfts** [comment]
Change the location by "long pressing on anywhere on the map"

**Comment by theebanka** [comment]
Oh you are a life saver! I was trying to get the magnifying glass to do something but it didn't seem to be doing anything! Not sure if I would have thought to long press :)

**Comment by mfts** [comment]
Magnifying glass is a bit misleading. It just basically zooms in on where you set the radar whereas the "pin" zooms in on your current location. Neither have an action that send data to the server.

**Comment by theebanka** [comment]
Ah yes I see that now! Since I couldn't set a position before it didn't seem to do anything! Thanks for all the help!
