### ISSUE TITLE
Scanning location not changing when moving

### ISSUE THREAD

**Issue by fraannk** [istornz/iPokeGo#9]
When I move around, the server still scans the area it was originally set up at. Shouldn't it use the user's location, and tell the server to scan there instead? Or alternatively make a location changer in settings. :) 

//fraannk

**Comment by istornz** [comment]
Yeah good idea !!
I'm going to work on it asap :)

**Comment by fraannk** [comment]
Nice. I'm thinking a "change location" box would be easiest, and you would not have to deal with too many location updates to the server. :)

**Comment by blackhattristar** [comment]
@fraannk The only problem with a "Change Location" box is that it requires the Google Places API Web Service which only allows 1,000 requests per day if you're not paying for it. Hope this helps!

**Comment by fraannk** [comment]
@blackhattristar Yeah, but wouldn't it at least be better than making it update from the users location? The 1000 requests would run out pretty fast if I walked 100m and the GPS kept updating the server :)

**Comment by fraannk** [comment]
I actually just saw this on the Android port: [https://camo.githubusercontent.com/2034f23f3ee3ede6fb1ff0b69956c6f6671ff72f/687474703a2f2f696d6775722e636f6d2f74744b573559572e706e67](Image) 
Long pressing to change scanning location sounds awesome! I vote for that solution :D

**Comment by a-moss** [comment]
Going off of what @fraannk said, this is rather easy.

We can just add a UILongPressGestureRecognizer to the map view and when the location is confirmed we can send a post request to the server to change the location:

SERVER_ADDRESS/next_loc?lat=LATITUDE&lon=LONGITUDE

If I have time I'll make a pull request for this.

**Comment by istornz** [comment]
I made change, now it's possible to change radar position by long press on the map :)

**Comment by blackhattristar** [comment]
@istornz Awesome! Will try now.

**Comment by blackhattristar** [comment]
@istornz It doesn't seem to be working. What do I need to do? I downloaded the latest zip and launched the app, put my host in the server input and when to my current location and it does not scan.

**Comment by blackhattristar** [comment]
@istornz When I load the app for the first time i get this error: 

Error Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x7fc8d00f6220 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL}}}

This error just keeps popping up constantly in the output. Any help would be greatly appreciated!

**Comment by blackhattristar** [comment]
@istornz Just a side note, I would still like to figure out the above error but I also got the Pokémon to load once I did a long press on the map. Is there no way to click the Go To Current Location button and THEN the Scan button to Scan at my current location so I don't have to long press at new locations?

**Comment by istornz** [comment]
Do you have the V2 version of the server ?

**Comment by blackhattristar** [comment]
@istornz You mean [PokemonMap](https://github.com/AHAAAAAAA/PokemonGo-Map)?

**Comment by istornz** [comment]
Yes

**Comment by blackhattristar** [comment]
@istornz I don't see a new release but I can download the current zip and try that. Will that change the beginning error I was getting?

**Comment by istornz** [comment]
This is this version : https://github.com/AHAAAAAAA/PokemonGo-Map/tree/V2.0
And I think yes

**Comment by blackhattristar** [comment]
@istornz I'll give that a try right now. Will that mean that I can scan depending on current location or do I still have to long press on a location in order to scan the map?

**Comment by istornz** [comment]
Long press for now. I will add scan for current location later

**Comment by blackhattristar** [comment]
@istornz I'm still getting the same error in the output console even with version 2.0

Do I have to run:

 python runserver.py -a google -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]"  in

Instead of the old one which didn't have Google Maps API Key? Because my google maps api key is already in the credentials folder.

**Comment by blackhattristar** [comment]
@istornz Food for thought... the only time I don't get the error message is once I've entered in a Server option. Then the error does not show up. Then the program does its thing. Is there a way to preload a server so that on first launch it has a server setup?

**Comment by istornz** [comment]
I made a fix. Please delete the app and re-install it :)

**Comment by blackhattristar** [comment]
@istornz That seems to have fixed the error message! Nice one. 

Is there any way I can set the server before hand in the code so that it loads with my server already in use?

I also noticed that PokéStops is not active when the app starts and when switch to on, no PokéStops show up. I don't really care for PokéStops but I thought i'd mention it.

**Comment by fraannk** [comment]
I'll mark this as fixed. Love the implementation of long press to change location. Thanks guys! :)
