### ISSUE TITLE
Inconsistent # of pokemons compared to server

### ISSUE THREAD

**Issue by mfts** [istornz/iPokeGo#90]
So I was wondering why I don't get all the pokemons on the iOS client compared to the webclient run on a Heroku server).

I limited the Step_Count from 5 to 3 (because perhaps it took too long to iterate over all steps and there were cached pokemons on the client)
Next I cleared the cache on both ios and web.

I still see an inconsistent number of pokemons appearing for the ios client vs the web client. roughly 1 in 5 Pokemons appears on iOS vs the web. Anyone got an idea. 

Webclient: (jigglypuff and spearow near the pin are here)
![screen shot 2016-07-29 at 14 10 30](https://cloud.githubusercontent.com/assets/4049052/17264389/7610ca08-559b-11e6-9eaa-558f5994c52d.png)

iOS client: (jigglypuff and spearow near the grey radar are *not* here)
![13866520_10154390180276018_1121170570_n](https://cloud.githubusercontent.com/assets/4049052/17264399/86a8b40c-559b-11e6-8a92-f61efccf9751.jpg)

Spec:
I'm running the master branch (as of today) on the server and the latest commit on the ios version

**Comment by istornz** [comment]
I was just looking at this issue more closely.
It's very strange because Pokemons that do not appear in the iOS app are not present in the JSON file (the API), so it does not come directly from the iOS app because it will "read" this file...
I also noticed that Pokemons that do not appear had a de-spawn period of quite low (<1min).
I will try with an older version and the develop version of the server.
Have you ever encountered this problem before?

**Comment by mfts** [comment]
Ah I think I know what the problem is: I'm actually running the master branch on the server, not the v2.0.0 (sorry about that; *changed above).

So those pokemons I didn't see on the iOS client actually spawned from a lure! I think I read that they added lured pokemons to a separate JSON (https://github.com/AHAAAAAAA/PokemonGo-Map/commit/b1fdac07b663244ee72671de055de323450605e1). Have you taken a look at that? Should I open a FR for "lured pokemons"?

**Comment by istornz** [comment]
Oh okay !
I have also updated my server version with the master version today :)

**Comment by istornz** [comment]
And I think you give me the wrong commit url :/

**Comment by mfts** [comment]
Sorry :( 

I just pulled the v2.1.0 because it seems most stable and it has the *lured pokemons* in there as well.

I'm gonna amend your api call in MapViewController / loadData and see if I can pull the lured pokemons as well

**Comment by mostafaelhefnawy** [comment]
@istornz i have this problem as well. My server has way more pokemon than in the iPokego app. Have you fixed it? Is there anything I need to do on my side to fix it?
