### ISSUE TITLE
Feature Requst: add a login for opening up the server Ip on the internet browser or ipokego

### ISSUE THREAD

**Issue by wardude202** [istornz/iPokeGo#91]
As the title says, if this is possible could someone guide me through how to do it

**Comment by markvl91** [comment]
Duplicate of #72?

**Comment by INGY23** [comment]
Guessing not, I believe what wardude is after is a way of securing the webpage so that it asks for a username and password when opening so other people can't use it.

**Comment by wardude202** [comment]
That's exactly what I'd love @INGY

**Comment by istornz** [comment]
@wardude202 @INGY23 Can you give me in mp any server with this protection ?

**Comment by istornz** [comment]
Now added in the latest build. I close
