### ISSUE TITLE
Failure to setup sound

### ISSUE THREAD

**Issue by blackhattristar** [istornz/iPokeGo#92]
I'm getting this error message in the console when changing location

"Failure to setup sound, err = -50"

**Comment by istornz** [comment]
What is you iDevice ?

**Comment by blackhattristar** [comment]
I'm running an iPhone 6 Plus with the latest software version 9.3.3

**Comment by istornz** [comment]
Do you test the app on simulator or on your real device ?

**Comment by istornz** [comment]
I close the issue, please open an another issue if you still have this problem.
