### ISSUE TITLE
New app version don't work with Heroku hosted server

### ISSUE THREAD

**Issue by QuentR** [istornz/iPokeGo#95]
Hi guys, 
I've downloaded the latest version of the app, and the Pokemon search don't work anymore.
I'm using a Heroku server, (latest uptade of the python), and when I start the app, Xcode show me this error : 
UserInfo={NSErrorFailingURLStringKey=MYHEROKUAPPSERVERADDRESS/raw_data?pokemon=true&pokestops=true&gyms=false, NSLocalizedDescription=URL non gérée, NSErrorFailingURLKey=MYHEROKUAPPSERVERADDRESS/raw_data?pokemon=true&pokestops=true&gyms=false}}, NSErrorFailingURLStringKey=MYHEROKUAPPSERVERADDRESS/raw_data?pokemon=true&pokestops=true&gyms=false, NSErrorFailingURLKey=MYHEROKUAPPSERVERADDRESS/raw_data?pokemon=true&pokestops=true&gyms=false, NSLocalizedDescription=URL non gérée}

Any ideas ? 

NOTE : With the old version of iPokeGo it work perfectly

Many thanks for your work ;)

**Comment by istornz** [comment]
Do you have added "https://" before server url ?
Note the "S" inside "httpS://"

**Comment by siideffect** [comment]
Hello istornz, i can confirm the same problem. Seems app update broke something. Yesterday it worked greatly but now it doesnt display any pokemon anymore . 
The url is https and the server is on heroku, any suggestion?
ps, you did an awesome work =)

**Comment by istornz** [comment]
@siideffect It seem Niantic block heroku server request... #106

**Comment by siideffect** [comment]
@istornz any suggestion in order to make it work again?
