### ISSUE TITLE
Spanish localisation isn't working

### ISSUE THREAD

**Issue by SrGMC** [istornz/iPokeGo#97]
I've built the recent version of the project and I've seen that the Spanish localisation is not working (and I think Russian isn't working too).

I think I was because I forgot to add the translates files to the Xcode project, and I don't know where to add them

**Comment by markvl91** [comment]
I can't find any Spanish localisations in the project, so you would be correct. Can you double-check if  the Russian isn't working?

**Comment by SrGMC** [comment]
@markvl91 Russian is working.
The only problem is with Spanish translations. I only added the files but not to the project (duh...)
