### ISSUE TITLE
Pokémons selected aren't marked on list

### ISSUE THREAD

**Issue by SrGMC** [istornz/iPokeGo#98]
After I select a Pokémon (Favorites or Common), when I save and I get back, the selected tick isn't showing, but I still get notified and it hides them on the map also. It still happens after reinstalling the app.

I've attached some screenshots showing the bug:

![img_2549](https://cloud.githubusercontent.com/assets/8809764/17273200/dfb08b94-56ac-11e6-82c5-da8a6c1eb66f.PNG)
![img_2550](https://cloud.githubusercontent.com/assets/8809764/17273201/dfdc4216-56ac-11e6-97a5-287ee7e0e2ed.PNG)

**Comment by markvl91** [comment]
It's working just fine on my end, any chance you can share the Xcode console logs?
